import { BoneHealthZone } from "../types";

export const generalSystemicZone: BoneHealthZone = {
  id: "general_systemic",
  name: "General / Systemic",
  anatomicalFocus: "Overall Bone Metabolism & Health",
  position: { x: 50, y: 45 },
  overallRisk: "low",
  riskFactors: ["Age-related bone loss", "Sedentary lifestyle"],
  lastAssessment: "2024-01-15",
  recommendations: [
    "Maintain adequate Vitamin D supplementation (2000-4000 IU daily)",
    "Ensure calcium intake of 1000-1200mg daily from food and supplements",
    "Weight-bearing exercise 3-4x per week for bone density",
    "Monitor bone turnover markers every 6 months",
    "Consider magnesium supplementation (400-600mg daily)",
  ],
  biomarkers: [
    {
      name: "Vitamin D (25-OH)",
      value: 45,
      unit: "ng/mL",
      referenceRange: "30-100",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Essential for calcium absorption and bone mineralization",
    },
    {
      name: "Calcium (Total)",
      value: 9.8,
      unit: "mg/dL",
      referenceRange: "8.5-10.5",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Primary mineral component of bone tissue",
    },
    {
      name: "Phosphorus",
      value: 3.2,
      unit: "mg/dL",
      referenceRange: "2.5-4.5",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Works with calcium for bone and teeth formation",
    },
    {
      name: "Magnesium",
      value: 1.9,
      unit: "mg/dL",
      referenceRange: "1.7-2.2",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Cofactor for bone formation and vitamin D metabolism",
    },
    {
      name: "Zinc",
      value: 85,
      unit: "μg/dL",
      referenceRange: "60-120",
      status: "normal",
      lastUpdated: "2024-01-15",
      description: "Essential trace element for bone formation",
    },
    {
      name: "Copper",
      value: 95,
      unit: "μg/dL",
      referenceRange: "70-140",
      status: "normal",
      lastUpdated: "2024-01-15",
      description: "Required for collagen cross-linking in bone",
    },
    {
      name: "PTH (Intact)",
      value: 35,
      unit: "pg/mL",
      referenceRange: "15-65",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Parathyroid hormone regulating calcium and phosphate",
    },
    {
      name: "CRP (hs-CRP)",
      value: 1.2,
      unit: "mg/L",
      referenceRange: "<3.0",
      status: "normal",
      lastUpdated: "2024-01-15",
      description: "Inflammatory marker affecting bone metabolism",
    },
    {
      name: "ESR",
      value: 8,
      unit: "mm/hr",
      referenceRange: "<20",
      status: "normal",
      lastUpdated: "2024-01-15",
      description: "Erythrocyte sedimentation rate - inflammation marker",
    },
    {
      name: "BSAP",
      value: 18,
      unit: "μg/L",
      referenceRange: "6.5-20.1",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Bone-specific alkaline phosphatase - bone formation marker",
    },
    {
      name: "Osteocalcin",
      value: 22,
      unit: "ng/mL",
      referenceRange: "11-43",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Bone formation marker produced by osteoblasts",
    },
    {
      name: "P1NP",
      value: 45,
      unit: "ng/mL",
      referenceRange: "16.3-78.1",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "Procollagen type 1 N-terminal propeptide - bone formation",
    },
    {
      name: "CTX",
      value: 0.35,
      unit: "ng/mL",
      referenceRange: "0.104-0.704",
      status: "normal",
      lastUpdated: "2024-01-15",
      trend: "stable",
      description: "C-terminal telopeptide - bone resorption marker",
    },
    {
      name: "NTX",
      value: 15,
      unit: "nmol BCE/mmol Cr",
      referenceRange: "5.4-24.2",
      status: "normal",
      lastUpdated: "2024-01-15",
      description: "N-terminal telopeptide - bone resorption marker",
    },
    {
      name: "TRACP-5b",
      value: 3.2,
      unit: "U/L",
      referenceRange: "1.03-4.15",
      status: "normal",
      lastUpdated: "2024-01-15",
      description: "Tartrate-resistant acid phosphatase - osteoclast marker",
    },
  ],
};
