import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#000000' },
  keyboardContainer: { flex: 1 },
  messagesContainer: { flex: 1, backgroundColor: 'transparent' },
  messagesContent: { paddingHorizontal: 4, paddingBottom: 20 },
  assistantAvatar: { width: 28, height: 28, borderRadius: 14, backgroundColor: '#3AABF020', alignItems: 'center', justifyContent: 'center', marginRight: 8, marginTop: 4, borderWidth: 1, borderColor: '#3AABF030' },
  loadingContainer: { flexDirection: 'row', alignItems: 'center', marginVertical: 8, paddingHorizontal: 16 },
  loadingContent: { marginLeft: 12, flexDirection: 'row', alignItems: 'center' },
  loadingDots: { flexDirection: 'row', alignItems: 'center', marginBottom: 8 },
  loadingDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#3AABF0', marginHorizontal: 3 },
  confirmBar: { backgroundColor: '#1E293B', borderTopWidth: 1, borderTopColor: '#0F172A', paddingHorizontal: 12, paddingVertical: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  confirmText: { color: '#E2E8F0', fontSize: 14, fontWeight: '600', marginRight: 12, flex: 1 },
  confirmBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 10, marginLeft: 8 },
  confirmBtnPrimary: { backgroundColor: '#10B981' },
  confirmBtnSecondary: { backgroundColor: '#334155' },
  confirmBtnText: { color: '#FFFFFF', fontWeight: '700', fontSize: 12 },
  historyLinkRow: { paddingHorizontal: 16, marginTop: 6, marginBottom: 4, alignItems: 'flex-end' },
  historyLinkText: { color: '#93C5FD', fontWeight: '700', fontSize: 12 },
  planContainer: { marginTop: 8 },
  planHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, marginBottom: 4 },
  planHeaderText: { color: '#E5E7EB', fontSize: 14, fontWeight: '700' },
  planCompletion: { color: '#9CA3AF', fontSize: 12, fontWeight: '700' },
  ashOverlay: { position: 'absolute', justifyContent: 'center', alignItems: 'center', overflow: 'visible', zIndex: 1000 },
  historyOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.55)', alignItems: 'center', justifyContent: 'center', padding: 16 },
  historyCard: { width: '100%', maxWidth: 420, height: '70%', backgroundColor: '#111827', borderRadius: 16, borderWidth: 1, borderColor: '#1F2937', padding: 12 },
  historyHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 4, paddingVertical: 6, marginBottom: 4 },
  historyTitle: { color: '#E5E7EB', fontWeight: '800', fontSize: 16 },
  historyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', backgroundColor: '#000000', borderRadius: 12, paddingHorizontal: 12, paddingVertical: 10, marginHorizontal: 12, marginVertical: 6, borderWidth: 1, borderColor: '#1F2937' },
  historyRowTitle: { color: '#E5E7EB', fontSize: 14, fontWeight: '600' },
  historyRowMeta: { color: '#6B7280', fontSize: 12, marginTop: 2 },
  historyProgress: { color: '#93C5FD', fontWeight: '700', fontSize: 13 },
  centeredFill: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 16 },
  mutedText: { color: '#6B7280', fontSize: 14, marginTop: 8 },
  retryButton: { marginTop: 12, paddingHorizontal: 20, paddingVertical: 8, backgroundColor: '#1F2937', borderRadius: 8 },
  chatDrawer: { width: '75%', height: '100%', backgroundColor: '#0B0B0F', paddingTop: 60, borderRightWidth: 0.5, borderRightColor: '#1F2937' },
  chatDrawerHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 16, paddingBottom: 16, borderBottomWidth: 0.5, borderBottomColor: '#1F2937' },
  chatDrawerTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  newChatModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'flex-end' },
  newChatBottomSheetContainer: { width: '100%' },
  newChatBottomSheetContent: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, paddingBottom: 34 },
  newChatBottomSheetHandleContainer: { alignItems: 'center', paddingTop: 8, paddingBottom: 4 },
  newChatBottomSheetHandle: { width: 40, height: 4, borderRadius: 2, backgroundColor: '#3A3A3C' },
  newChatBottomSheetHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 12 },
  newChatBottomSheetTitle: { color: '#FFFFFF', fontSize: 17, fontWeight: '600', flex: 1, textAlign: 'center' },
  newChatBottomSheetCloseButton: { width: 32, height: 32, alignItems: 'center', justifyContent: 'center' },
  newChatBottomSheetBody: { paddingHorizontal: 20, paddingTop: 8 },
  newChatQuestion: { color: '#EBEBF5', fontSize: 16, marginBottom: 20, textAlign: 'center' },
  newChatButtonWithMemory: { backgroundColor: '#3AABF0', borderRadius: 12, paddingVertical: 14, alignItems: 'center', marginBottom: 12 },
  newChatButtonNoMemory: { backgroundColor: '#2C2C2E', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  newChatButtonText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
  imageModalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  imageModalCard: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 40 },
  imageModalHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 16 },
  imageModalTitle: { color: '#FFFFFF', fontSize: 18, fontWeight: '700' },
  imagePreview: { width: '100%', height: 200, borderRadius: 12 },
  imageInputField: { backgroundColor: '#2C2C2E', borderRadius: 12, padding: 12, color: '#FFFFFF', fontSize: 16, minHeight: 80, marginBottom: 16, textAlignVertical: 'top' },
  imageModalCancelBtn: { flex: 1, backgroundColor: '#2C2C2E', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  imageModalSendBtn: { flex: 1, backgroundColor: '#3AABF0', borderRadius: 12, paddingVertical: 14, alignItems: 'center' },
  imageModalBtnText: { color: '#FFFFFF', fontSize: 16, fontWeight: '600' },
});
