import { StyleSheet } from 'react-native';

export const formModalStyles = StyleSheet.create({
  overlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  sheet: { backgroundColor: '#1C1C1E', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '90%' },
  header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 20, paddingVertical: 16, borderBottomWidth: 1, borderBottomColor: '#2C2C2E' },
  title: { fontSize: 18, fontWeight: '700', color: '#FFFFFF' },
  body: { padding: 20, paddingBottom: 40 },
  group: { backgroundColor: '#2C2C2E', borderRadius: 12, overflow: 'hidden' },
  input: { paddingHorizontal: 16, paddingVertical: 13, fontSize: 16, color: '#FFFFFF' },
  divider: { height: 1, backgroundColor: '#3A3A3C', marginLeft: 16 },
  sectionLabel: { fontSize: 13, fontWeight: '600', color: '#8E8E93', marginTop: 20, marginBottom: 10, marginLeft: 4, textTransform: 'uppercase', letterSpacing: 0.5 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 20, backgroundColor: '#2C2C2E', borderWidth: 1, borderColor: '#3A3A3C' },
  chipActive: { backgroundColor: '#3AABF0', borderColor: '#3AABF0' },
  chipText: { color: '#FFFFFF', fontSize: 14 },
  chipTextActive: { color: '#FFFFFF', fontWeight: '600' },
  dateRow: { backgroundColor: '#2C2C2E', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 13, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 8 },
  dateText: { fontSize: 16, color: '#FFFFFF' },
  placeholder: { color: '#8E8E93' },
  suggestions: { backgroundColor: '#3A3A3C', marginHorizontal: 16, borderRadius: 8, marginBottom: 4 },
  suggestionItem: { paddingHorizontal: 16, paddingVertical: 12 },
  suggestionText: { color: '#FFFFFF', fontSize: 16 },
  attachRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, alignItems: 'center' },
  attachChip: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#2C2C2E', borderRadius: 16, paddingHorizontal: 10, paddingVertical: 6, borderWidth: 1, borderColor: '#3A3A3C' },
  attachText: { color: '#FFFFFF', fontSize: 12, marginLeft: 6, maxWidth: 140 },
  addAttach: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#1C1C1E', borderRadius: 16, paddingHorizontal: 12, paddingVertical: 8, borderWidth: 1, borderColor: '#3AABF0' },
  addAttachText: { color: '#3AABF0', fontSize: 12, marginLeft: 6, fontWeight: '600' },
  attachHelp: { marginTop: 8, color: '#8E8E93', fontSize: 12 },
});
