import React, { useMemo, useState } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, Platform } from 'react-native';
import { Ionicons } from '@expo/vector-icons';
import { useNavigation } from '@react-navigation/native';
import { StackNavigationProp } from '@react-navigation/stack';
import { ProfileTabParamList } from '../../types';
import { colors } from '../../theme/colors';

type Nav = StackNavigationProp<ProfileTabParamList, 'CountryLeaderboard'>;

const SF_FONT = Platform.select({ ios: 'SF Pro Text', android: 'System' }) ?? 'System';

const CountryLeaderboardScreen: React.FC = () => {
  const navigation = useNavigation<Nav>();
  const [joinedCountry, setJoinedCountry] = useState(false);

  const countryAverages = useMemo(() => {
    const countries = [
      { name: 'Afghanistan', code: 'AF' },
      { name: 'Albania', code: 'AL' },
      { name: 'Algeria', code: 'DZ' },
      { name: 'Andorra', code: 'AD' },
      { name: 'Angola', code: 'AO' },
      { name: 'Antigua and Barbuda', code: 'AG' },
      { name: 'Argentina', code: 'AR' },
      { name: 'Armenia', code: 'AM' },
      { name: 'Australia', code: 'AU' },
      { name: 'Austria', code: 'AT' },
      { name: 'Azerbaijan', code: 'AZ' },
      { name: 'Bahamas', code: 'BS' },
      { name: 'Bahrain', code: 'BH' },
      { name: 'Bangladesh', code: 'BD' },
      { name: 'Barbados', code: 'BB' },
      { name: 'Belarus', code: 'BY' },
      { name: 'Belgium', code: 'BE' },
      { name: 'Belize', code: 'BZ' },
      { name: 'Benin', code: 'BJ' },
      { name: 'Bhutan', code: 'BT' },
      { name: 'Bolivia', code: 'BO' },
      { name: 'Bosnia and Herzegovina', code: 'BA' },
      { name: 'Botswana', code: 'BW' },
      { name: 'Brazil', code: 'BR' },
      { name: 'Brunei', code: 'BN' },
      { name: 'Bulgaria', code: 'BG' },
      { name: 'Burkina Faso', code: 'BF' },
      { name: 'Burundi', code: 'BI' },
      { name: 'Cabo Verde', code: 'CV' },
      { name: 'Cambodia', code: 'KH' },
      { name: 'Cameroon', code: 'CM' },
      { name: 'Canada', code: 'CA' },
      { name: 'Central African Republic', code: 'CF' },
      { name: 'Chad', code: 'TD' },
      { name: 'Chile', code: 'CL' },
      { name: 'China', code: 'CN' },
      { name: 'Colombia', code: 'CO' },
      { name: 'Comoros', code: 'KM' },
      { name: 'Congo (Congo-Brazzaville)', code: 'CG' },
      { name: 'Costa Rica', code: 'CR' },
      { name: 'Croatia', code: 'HR' },
      { name: 'Cuba', code: 'CU' },
      { name: 'Cyprus', code: 'CY' },
      { name: 'Czechia', code: 'CZ' },
      { name: 'Democratic Republic of the Congo', code: 'CD' },
      { name: 'Denmark', code: 'DK' },
      { name: 'Djibouti', code: 'DJ' },
      { name: 'Dominica', code: 'DM' },
      { name: 'Dominican Republic', code: 'DO' },
      { name: 'Ecuador', code: 'EC' },
      { name: 'Egypt', code: 'EG' },
      { name: 'El Salvador', code: 'SV' },
      { name: 'Equatorial Guinea', code: 'GQ' },
      { name: 'Eritrea', code: 'ER' },
      { name: 'Estonia', code: 'EE' },
      { name: 'Eswatini', code: 'SZ' },
      { name: 'Ethiopia', code: 'ET' },
      { name: 'Fiji', code: 'FJ' },
      { name: 'Finland', code: 'FI' },
      { name: 'France', code: 'FR' },
      { name: 'Gabon', code: 'GA' },
      { name: 'Gambia', code: 'GM' },
      { name: 'Georgia', code: 'GE' },
      { name: 'Germany', code: 'DE' },
      { name: 'Ghana', code: 'GH' },
      { name: 'Greece', code: 'GR' },
      { name: 'Grenada', code: 'GD' },
      { name: 'Guatemala', code: 'GT' },
      { name: 'Guinea', code: 'GN' },
      { name: 'Guinea-Bissau', code: 'GW' },
      { name: 'Guyana', code: 'GY' },
      { name: 'Haiti', code: 'HT' },
      { name: 'Honduras', code: 'HN' },
      { name: 'Hungary', code: 'HU' },
      { name: 'Iceland', code: 'IS' },
      { name: 'India', code: 'IN' },
      { name: 'Indonesia', code: 'ID' },
      { name: 'Iran', code: 'IR' },
      { name: 'Iraq', code: 'IQ' },
      { name: 'Ireland', code: 'IE' },
      { name: 'Israel', code: 'IL' },
      { name: 'Italy', code: 'IT' },
      { name: 'Jamaica', code: 'JM' },
      { name: 'Japan', code: 'JP' },
      { name: 'Jordan', code: 'JO' },
      { name: 'Kazakhstan', code: 'KZ' },
      { name: 'Kenya', code: 'KE' },
      { name: 'Kiribati', code: 'KI' },
      { name: 'Kuwait', code: 'KW' },
      { name: 'Kyrgyzstan', code: 'KG' },
      { name: 'Laos', code: 'LA' },
      { name: 'Latvia', code: 'LV' },
      { name: 'Lebanon', code: 'LB' },
      { name: 'Lesotho', code: 'LS' },
      { name: 'Liberia', code: 'LR' },
      { name: 'Libya', code: 'LY' },
      { name: 'Liechtenstein', code: 'LI' },
      { name: 'Lithuania', code: 'LT' },
      { name: 'Luxembourg', code: 'LU' },
      { name: 'Madagascar', code: 'MG' },
      { name: 'Malawi', code: 'MW' },
      { name: 'Malaysia', code: 'MY' },
      { name: 'Maldives', code: 'MV' },
      { name: 'Mali', code: 'ML' },
      { name: 'Malta', code: 'MT' },
      { name: 'Marshall Islands', code: 'MH' },
      { name: 'Mauritania', code: 'MR' },
      { name: 'Mauritius', code: 'MU' },
      { name: 'Mexico', code: 'MX' },
      { name: 'Micronesia', code: 'FM' },
      { name: 'Moldova', code: 'MD' },
      { name: 'Monaco', code: 'MC' },
      { name: 'Mongolia', code: 'MN' },
      { name: 'Montenegro', code: 'ME' },
      { name: 'Morocco', code: 'MA' },
      { name: 'Mozambique', code: 'MZ' },
      { name: 'Myanmar', code: 'MM' },
      { name: 'Namibia', code: 'NA' },
      { name: 'Nauru', code: 'NR' },
      { name: 'Nepal', code: 'NP' },
      { name: 'Netherlands', code: 'NL' },
      { name: 'New Zealand', code: 'NZ' },
      { name: 'Nicaragua', code: 'NI' },
      { name: 'Niger', code: 'NE' },
      { name: 'Nigeria', code: 'NG' },
      { name: 'North Korea', code: 'KP' },
      { name: 'North Macedonia', code: 'MK' },
      { name: 'Norway', code: 'NO' },
      { name: 'Oman', code: 'OM' },
      { name: 'Pakistan', code: 'PK' },
      { name: 'Palau', code: 'PW' },
      { name: 'Panama', code: 'PA' },
      { name: 'Papua New Guinea', code: 'PG' },
      { name: 'Paraguay', code: 'PY' },
      { name: 'Peru', code: 'PE' },
      { name: 'Philippines', code: 'PH' },
      { name: 'Poland', code: 'PL' },
      { name: 'Portugal', code: 'PT' },
      { name: 'Qatar', code: 'QA' },
      { name: 'Romania', code: 'RO' },
      { name: 'Russia', code: 'RU' },
      { name: 'Rwanda', code: 'RW' },
      { name: 'Saint Kitts and Nevis', code: 'KN' },
      { name: 'Saint Lucia', code: 'LC' },
      { name: 'Saint Vincent and the Grenadines', code: 'VC' },
      { name: 'Samoa', code: 'WS' },
      { name: 'San Marino', code: 'SM' },
      { name: 'Sao Tome and Principe', code: 'ST' },
      { name: 'Saudi Arabia', code: 'SA' },
      { name: 'Senegal', code: 'SN' },
      { name: 'Serbia', code: 'RS' },
      { name: 'Seychelles', code: 'SC' },
      { name: 'Sierra Leone', code: 'SL' },
      { name: 'Singapore', code: 'SG' },
      { name: 'Slovakia', code: 'SK' },
      { name: 'Slovenia', code: 'SI' },
      { name: 'Solomon Islands', code: 'SB' },
      { name: 'Somalia', code: 'SO' },
      { name: 'South Africa', code: 'ZA' },
      { name: 'South Korea', code: 'KR' },
      { name: 'South Sudan', code: 'SS' },
      { name: 'Spain', code: 'ES' },
      { name: 'Sri Lanka', code: 'LK' },
      { name: 'Sudan', code: 'SD' },
      { name: 'Suriname', code: 'SR' },
      { name: 'Sweden', code: 'SE' },
      { name: 'Switzerland', code: 'CH' },
      { name: 'Syria', code: 'SY' },
      { name: 'Taiwan', code: 'TW' },
      { name: 'Tajikistan', code: 'TJ' },
      { name: 'Tanzania', code: 'TZ' },
      { name: 'Thailand', code: 'TH' },
      { name: 'Timor-Leste', code: 'TL' },
      { name: 'Togo', code: 'TG' },
      { name: 'Tonga', code: 'TO' },
      { name: 'Trinidad and Tobago', code: 'TT' },
      { name: 'Tunisia', code: 'TN' },
      { name: 'Turkey', code: 'TR' },
      { name: 'Turkmenistan', code: 'TM' },
      { name: 'Tuvalu', code: 'TV' },
      { name: 'Uganda', code: 'UG' },
      { name: 'Ukraine', code: 'UA' },
      { name: 'United Arab Emirates', code: 'AE' },
      { name: 'United Kingdom', code: 'GB' },
      { name: 'United States', code: 'US' },
      { name: 'Uruguay', code: 'UY' },
      { name: 'Uzbekistan', code: 'UZ' },
      { name: 'Vanuatu', code: 'VU' },
      { name: 'Vatican City', code: 'VA' },
      { name: 'Venezuela', code: 'VE' },
      { name: 'Vietnam', code: 'VN' },
      { name: 'Yemen', code: 'YE' },
      { name: 'Zambia', code: 'ZM' },
      { name: 'Zimbabwe', code: 'ZW' },
      { name: 'Kosovo', code: 'XK' },
      { name: 'Palestine', code: 'PS' },
      { name: 'Hong Kong SAR, China', code: 'HK' },
      { name: 'Macao SAR, China', code: 'MO' },
      { name: 'Channel Islands', code: 'JE' },
      { name: 'Faroe Islands', code: 'FO' },
      { name: 'Bermuda', code: 'BM' },
      { name: 'Guam', code: 'GU' },
      { name: 'St. Martin (French part)', code: 'MF' },
      { name: 'Puerto Rico', code: 'PR' },
      { name: 'Virgin Islands (U.S.)', code: 'VI' },
      { name: 'French Polynesia', code: 'PF' },
      { name: 'New Caledonia', code: 'NC' },
      { name: 'Aruba', code: 'AW' },
      { name: 'Cote d’Ivoire', code: 'CI' },
    ];

    const byName = new Map(countries.map((c) => [c.name, c.code]));
    const aliases: Record<string, string> = {
      'Korea, Rep.': 'South Korea',
      'Iran, Islamic Rep.': 'Iran',
      'Czech Republic': 'Czechia',
      'Slovak Republic': 'Slovakia',
      'Bahamas, The': 'Bahamas',
      'Congo, Rep.': 'Congo (Congo-Brazzaville)',
      'Congo, Dem. Rep.': 'Democratic Republic of the Congo',
      'Gambia, The': 'Gambia',
      'West Bank and Gaza': 'Palestine',
      'Brunei Darussalam': 'Brunei',
      'Lao PDR': 'Laos',
      'Micronesia, Fed. Sts.': 'Micronesia',
      'Yemen, Rep.': 'Yemen',
      'St. Lucia': 'Saint Lucia',
      'St. Kitts and Nevis': 'Saint Kitts and Nevis',
      'St. Vincent and the Grenadines': 'Saint Vincent and the Grenadines',
      'Cote d\'Ivoire': 'Cote d’Ivoire',
    };

    const ranked = [
      { name: 'Hong Kong SAR, China', score: 85.0780487804878 },
      { name: 'Japan', score: 84.3563414634146 },
      { name: 'Macao SAR, China', score: 84.244 },
      { name: 'Switzerland', score: 83.7048780487805 },
      { name: 'Singapore', score: 83.4975609756098 },
      { name: 'Spain', score: 83.4853658536585 },
      { name: 'Korea, Rep.', score: 83.2268292682927 },
      { name: 'Italy', score: 83.1975609756098 },
      { name: 'Channel Islands', score: 83.086 },
      { name: 'Liechtenstein', score: 83.0414634146342 },
      { name: 'Sweden', score: 82.9585365853659 },
      { name: 'Norway', score: 82.9073170731707 },
      { name: 'Australia', score: 82.9 },
      { name: 'Israel', score: 82.8048780487805 },
      { name: 'Faroe Islands', score: 82.7463414634146 },
      { name: 'Malta', score: 82.6 },
      { name: 'France', score: 82.5780487804878 },
      { name: 'Iceland', score: 82.5609756097561 },
      { name: 'Luxembourg', score: 82.4463414634146 },
      { name: 'Ireland', score: 82.3024390243903 },
      { name: 'Canada', score: 82.0487804878049 },
      { name: 'Netherlands', score: 82.0121951219512 },
      { name: 'Greece', score: 81.9390243902439 },
      { name: 'Bermuda', score: 81.8658536585367 },
      { name: 'Austria', score: 81.7926829268293 },
      { name: 'Finland', score: 81.7853658536586 },
      { name: 'Belgium', score: 81.7463414634146 },
      { name: 'New Zealand', score: 81.7073170731707 },
      { name: 'Slovenia', score: 81.280487804878 },
      { name: 'United Kingdom', score: 81.2048780487805 },
      { name: 'Denmark', score: 81.2024390243903 },
      { name: 'Cyprus', score: 80.982 },
      { name: 'Germany' },
      { name: 'Portugal' },
      { name: 'Costa Rica' },
      { name: 'Qatar' },
      { name: 'Chile' },
      { name: 'Guam' },
      { name: 'St. Martin (French part)' },
      { name: 'Puerto Rico' },
      { name: 'Virgin Islands (U.S.)' },
      { name: 'Barbados' },
      { name: 'Czech Republic' },
      { name: 'Lebanon' },
      { name: 'Maldives' },
      { name: 'Cuba' },
      { name: 'United States' },
      { name: 'Albania' },
      { name: 'Panama' },
      { name: 'Estonia' },
      { name: 'Croatia' },
      { name: 'Uruguay' },
      { name: 'Oman' },
      { name: 'Poland' },
      { name: 'Turkey' },
      { name: 'French Polynesia' },
      { name: 'New Caledonia' },
      { name: 'Slovak Republic' },
      { name: 'Bosnia and Herzegovina' },
      { name: 'Bahrain' },
      { name: 'Colombia' },
      { name: 'Thailand' },
      { name: 'Antigua and Barbuda' },
      { name: 'Ecuador' },
      { name: 'Sri Lanka' },
      { name: 'China' },
      { name: 'Montenegro' },
      { name: 'Tunisia' },
      { name: 'Morocco' },
      { name: 'Iran, Islamic Rep.' },
      { name: 'Argentina' },
      { name: 'Aruba' },
      { name: 'St. Lucia' },
      { name: 'Malaysia' },
      { name: 'Lithuania' },
      { name: 'Hungary' },
      { name: 'Brazil' },
      { name: 'Brunei Darussalam' },
      { name: 'North Macedonia' },
      { name: 'Serbia' },
      { name: 'Kuwait' },
      { name: 'Romania' },
      { name: 'Vietnam' },
      { name: 'Honduras' },
      { name: 'Latvia' },
      { name: 'Armenia' },
      { name: 'Mexico' },
      { name: 'Bulgaria' },
      { name: 'Belize' },
      { name: 'Jordan' },
      { name: 'Nicaragua' },
      { name: 'Jamaica' },
      { name: 'Guatemala' },
      { name: 'Paraguay' },
      { name: 'Mauritius' },
      { name: 'Belarus' },
      { name: 'Dominican Republic' },
      { name: 'West Bank and Gaza' },
      { name: 'Seychelles' },
      { name: 'Bahamas, The' },
      { name: 'Georgia' },
      { name: 'Trinidad and Tobago' },
      { name: 'Samoa' },
      { name: 'El Salvador' },
      { name: 'Tajikistan' },
      { name: 'Tonga' },
      { name: 'Nepal' },
      { name: 'Iraq' },
      { name: 'Vanuatu' },
      { name: 'Sao Tome and Principe' },
      { name: 'Guyana' },
      { name: 'Mongolia' },
      { name: 'Cambodia' },
      { name: 'India' },
      { name: 'Botswana' },
      { name: 'Timor-Leste' },
      { name: 'Rwanda' },
      { name: 'Other small states' },
      { name: 'Kiribati' },
      { name: 'Turkmenistan' },
      { name: 'Senegal' },
      { name: 'Lao PDR' },
      { name: 'Micronesia, Fed. Sts.' },
      { name: 'Fiji' },
      { name: 'Pakistan' },
      { name: 'Myanmar' },
      { name: 'Djibouti' },
      { name: 'Madagascar' },
      { name: 'Kenya' },
      { name: 'Ethiopia' },
      { name: 'Gabon' },
      { name: 'Eritrea' },
      { name: 'Yemen, Rep.' },
      { name: 'Tanzania' },
      { name: 'Least developed countries' },
      { name: 'Sudan' },
      { name: 'Mauritania' },
      { name: 'Afghanistan' },
      { name: 'Congo, Rep.' },
      { name: 'Papua New Guinea' },
      { name: 'Comoros' },
      { name: 'Malawi' },
      { name: 'Liberia' },
      { name: 'Ghana' },
      { name: 'Haiti' },
      { name: 'Zambia' },
      { name: 'Namibia' },
      { name: 'Uganda' },
      { name: 'Niger' },
      { name: 'Gambia, The' },
      { name: 'Benin' },
      { name: 'Guinea' },
      { name: 'Burundi' },
      { name: 'Burkina Faso' },
      { name: 'Zimbabwe' },
      { name: 'Angola' },
      { name: 'Togo' },
      { name: 'Mozambique' },
      { name: 'Congo, Dem. Rep.' },
      { name: 'Eswatini' },
      { name: 'Mali' },
      { name: 'Cameroon' },
      { name: 'Equatorial Guinea' },
      { name: 'Guinea-Bissau' },
      { name: 'South Sudan' },
      { name: 'Cote d’Ivoire' },
      { name: 'Somalia' },
      { name: 'Sierra Leone' },
      { name: 'Nigeria' },
      { name: 'Lesotho' },
      { name: 'Chad' },
    ];

    const flagFromCode = (code: string) => {
      const upper = code.toUpperCase();
      const base = 0x1f1e6;
      const first = upper.charCodeAt(0) - 65 + base;
      const second = upper.charCodeAt(1) - 65 + base;
      return String.fromCodePoint(first, second);
    };

    return ranked.map((entry, idx) => {
      const name = entry.name;
      const alias = aliases[name];
      const code = byName.get(alias || name);
      return {
        name,
        flag: code ? flagFromCode(code) : '🌐',
        score: entry.score,
        delta: idx % 3 === 0 ? 1 : idx % 3 === 1 ? 0 : -1,
      };
    });
  }, []);

  const RankDelta = ({ delta }: { delta: number }) => {
    if (delta === 0) {
      return <View style={[styles.deltaBar, styles.deltaBarFlat]} />;
    }
    return (
      <Ionicons
        name={delta > 0 ? 'caret-up' : 'caret-down'}
        size={12}
        color={delta > 0 ? '#34C759' : '#FF453A'}
        style={styles.deltaIcon}
      />
    );
  };

  return (
    <View style={styles.container}>
      <View style={styles.headerRow}>
        <TouchableOpacity onPress={() => navigation.goBack()} style={styles.headerBackBtn} hitSlop={{ top: 12, bottom: 12, left: 12, right: 12 }}>
          <Ionicons name="chevron-back" size={24} color={colors.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Country Leaderboard</Text>
        <TouchableOpacity
          style={[styles.joinBtn, joinedCountry && styles.joinedBtn]}
          onPress={() => setJoinedCountry((prev) => !prev)}
          hitSlop={{ top: 8, bottom: 8, left: 8, right: 8 }}
        >
          <Text style={[styles.joinBtnText, joinedCountry && styles.joinedBtnText]}>
            {joinedCountry ? 'Joined' : 'Join'}
          </Text>
        </TouchableOpacity>
      </View>
      <ScrollView style={styles.scrollContent} showsVerticalScrollIndicator={false}>
        <View style={[styles.card, styles.leaderboardCard]}>
          {countryAverages.map((c, idx) => (
            <View key={c.name} style={styles.lbRow}>
              <Text style={styles.lbRank}>#{idx + 1}</Text>
              <Text style={styles.lbFlag}>{c.flag}</Text>
              <Text style={styles.lbName}>{c.name}</Text>
              <View style={styles.lbScoreRow}>
                <RankDelta delta={c.delta} />
              <Text style={styles.lbScore}>{typeof c.score === 'number' ? c.score.toFixed(1) : '—'}</Text>
              </View>
            </View>
          ))}
        </View>
        <View style={{ height: 24 }} />
      </ScrollView>
    </View>
  );
};

export default CountryLeaderboardScreen;

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: colors.bg },
  headerRow: { flexDirection: 'row', alignItems: 'center', paddingTop: 48, paddingHorizontal: 20, paddingBottom: 4, backgroundColor: colors.bg },
  scrollContent: { flex: 1 },
  headerBackBtn: { padding: 4 },
  headerBackSpacer: { width: 32, height: 32 },
  headerTitle: { flex: 1, color: colors.textPrimary, fontSize: 20, fontWeight: '600', textAlign: 'center', fontFamily: SF_FONT },
  joinBtn: {
    backgroundColor: colors.cta,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  joinBtnText: {
    color: colors.ctaText,
    fontSize: 12,
    fontWeight: '700',
    fontFamily: SF_FONT,
  },
  joinedBtn: {
    backgroundColor: colors.surfaceMuted,
  },
  joinedBtnText: {
    color: colors.textSecondary,
  },
  card: { backgroundColor: 'transparent', marginHorizontal: 20, marginBottom: 10, paddingVertical: 0, paddingHorizontal: 0 },
  leaderboardCard: { paddingTop: 0, paddingBottom: 0 },
  lbRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: colors.divider },
  lbRank: { color: colors.textSecondary, width: 40, fontSize: 13, fontFamily: SF_FONT },
  lbFlag: { width: 24, textAlign: 'center' },
  lbName: { color: colors.textPrimary, fontSize: 14, fontWeight: '600', flex: 1, fontFamily: SF_FONT },
  lbScoreRow: { flexDirection: 'row', alignItems: 'center', gap: 6, minWidth: 70, justifyContent: 'flex-end' },
  lbScore: { color: '#FFD60A', fontWeight: '700', textAlign: 'right', fontSize: 14, fontFamily: SF_FONT },
  deltaIcon: { marginTop: -1 },
  deltaBar: { width: 10, height: 2, borderRadius: 2, marginTop: 1 },
  deltaBarFlat: { backgroundColor: 'rgba(255,255,255,0.25)' },
});
