/**
 * Health alerts CRUD — serves the proactive alerts generated by the nightly trend analyzer.
 *
 * GET  /users/{userId}/alerts              → active (non-dismissed) alerts, newest first
 * PUT  /users/{userId}/alerts/{alertId}/dismiss → mark alert as dismissed
 */

import { APIGatewayProxyEvent, APIGatewayProxyResult } from 'aws-lambda';
import { getDb } from '../_shared/db';
import { ok, err } from '../_shared/response';
import { requireSelf } from '../_shared/auth';

export const handler = async (event: APIGatewayProxyEvent): Promise<APIGatewayProxyResult> => {
  const auth = requireSelf(event);
  if ('statusCode' in auth) return auth;
  const { userId } = auth;

  const db = await getDb();
  const method = event.httpMethod;
  const { alertId } = event.pathParameters ?? {};

  // PUT /users/{userId}/alerts/{alertId}/dismiss
  if (method === 'PUT' && alertId) {
    await db.query(
      `UPDATE health_alerts SET dismissed = true WHERE id = $1 AND user_id = $2`,
      [alertId, userId],
    );
    return ok({ dismissed: true });
  }

  // GET /users/{userId}/alerts
  if (method === 'GET') {
    const result = await db.query(
      `SELECT id, type, severity, title, body, biomarkers, dismissed, created_at
       FROM health_alerts
       WHERE user_id = $1 AND dismissed = false
       ORDER BY created_at DESC
       LIMIT 50`,
      [userId],
    );
    return ok(result.rows);
  }

  return err(405, 'Method not allowed');
};
