import { StyleSheet } from "react-native";
import { palette } from "../../../../../shared/theme/colors";

/** Vaccinations, health summary, metrics, trip cards, jet lag, date pickers, bottom sheet */
export const travelHealthTripsAndSheetsStyles = StyleSheet.create({
  vaccineRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "flex-start",
    backgroundColor: palette.surfaceElevated,
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 0,
    borderColor: palette.border,
  },
  vaccineLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    width: "50%",
  },
  vaccineRight: {
    width: "50%",
    alignItems: "flex-start",
  },
  vaccineName: {
    flex: 1,
    color: palette.textPrimary,
    fontWeight: "600",
    fontSize: 14,
  },
  vaccineBadge: {
    color: palette.textSecondary,
    fontSize: 12,
    marginLeft: 0,
  },

  summaryCard: {
    backgroundColor: palette.surfaceElevated,
    borderRadius: 16,
    padding: 16,
    marginBottom: 24,
    borderWidth: 0,
    borderColor: palette.border,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    marginLeft: 8,
  },
  summaryText: {
    fontSize: 14,
    color: palette.textSecondary,
  },
  metricsSection: {
    marginBottom: 28,
  },
  metricRowCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.surfaceElevated,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    borderWidth: 0,
    borderColor: palette.border,
  },

  metricIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  metricContent: {
    flex: 1,
  },

  metricName: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    marginBottom: 4,
  },
  metricValueText: {
    fontSize: 14,
    fontWeight: "500",
    color: palette.textPrimary,
    marginBottom: 4,
  },

  hospitalsSection: {
    marginBottom: 28,
  },
  sectionGroupCard: {
    backgroundColor: "transparent",
    borderRadius: 0,
    padding: 0,
    borderWidth: 0,
  },
  hospitalCard: {
    backgroundColor: palette.surfaceElevated,
    borderRadius: 16,
    padding: 16,
    marginBottom: 10,
    borderWidth: 0,
    borderColor: palette.border,
  },
  hospitalHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  hospitalTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    marginLeft: 8,
  },
  hospitalDistance: {
    fontSize: 13,
    color: palette.textSecondary,
    marginLeft: 8,
  },
  hospitalInfo: {
    fontSize: 14,
    color: palette.textSecondary,
  },
  medicationSection: {
    marginBottom: 20,
  },

  datePickerOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.8)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 10000,
    elevation: 10000,
  },
  datePickerModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10000,
  },
  datePickerModalContent: {
    backgroundColor: palette.surfaceElevated,
    borderRadius: 16,
    padding: 24,
    width: "90%",
    maxWidth: 400,
    alignItems: "center",
    borderWidth: 1,
    borderColor: palette.border,
    zIndex: 10001,
    elevation: 10001,
  },
  datePickerHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    alignSelf: "stretch",
    marginBottom: 16,
  },

  datePickerTitle: {
    flex: 1,
    fontSize: 20,
    fontWeight: "bold",
    color: palette.textPrimary,
    textAlign: "center",
  },

  datePicker: {
    width: "100%",
    backgroundColor: palette.surfaceElevated,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    color: palette.textPrimary,
  },

  emergencyModal: {
    backgroundColor: palette.surfaceElevated,
    borderRadius: 16,
    padding: 24,
    width: "80%",
    alignItems: "center",
    borderWidth: 1,
    borderColor: palette.border,
  },
  emergencyModalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: palette.textPrimary,
    marginBottom: 16,
  },
  emergencyModalButtons: {
    flexDirection: "row",
    justifyContent: "space-around",
    width: "100%",
    marginTop: 12,
  },
  emergencyCallButton: {
    backgroundColor: palette.danger,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emergencyCallButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    textAlign: "center",
  },
  emergencyCancelButton: {
    backgroundColor: palette.textSecondary,
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emergencyCancelButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    textAlign: "center",
  },
  resultTitleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: palette.textPrimary,
    flexShrink: 1,
  },

  metricRightCol: {
    alignItems: "flex-end",
    justifyContent: "center",
  },
  metricScoreText: {
    fontSize: 20,
    fontWeight: "bold",
    color: palette.textPrimary,
  },
  metricScoreLabelText: {
    fontSize: 12,
    color: palette.textSecondary,
    marginTop: 2,
  },
  // Bottom Sheet Styles
  bottomSheetContainer: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: "100%",
    zIndex: 1000,
    pointerEvents: "box-none",
    justifyContent: "flex-end",
  },
  bottomSheetContent: {
    flex: 1,
    backgroundColor: palette.surfaceElevated,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: "100%",
    minHeight: "70%",
    maxHeight: "100%",
    paddingBottom: 0,
    shadowColor: palette.bg,
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 16,
  },

  bottomSheetHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    zIndex: 10,
  },
  bottomSheetCloseButton: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
  },
  bottomSheetTitle: {
    fontSize: 22,
    fontWeight: "700",
    color: palette.textPrimary,
    textAlign: "center",
    flex: 1,
  },
  bottomSheetBody: {
    flex: 1,
  },
  bottomSheetBodyContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
});
