import { StyleSheet } from "react-native";
import { palette } from "../../../../../shared/theme/colors";

/** Metric detail modal, overlays, inputs, flight, search, suggestions, chips */
export const travelModalsAndFormsStyles = StyleSheet.create({
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  bottomSheetOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "flex-end",
    alignItems: "stretch",
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: palette.surface,
    borderRadius: 16,
    padding: 24,
    width: "80%",
    maxHeight: "80%",
    borderWidth: 0,
    borderColor: palette.border,
  },
  modalScrollContent: {
    width: "100%",
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    width: "100%",
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: palette.textPrimary,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    marginBottom: 8,
    alignSelf: "flex-start",
  },
  inputContainer: {
    width: "100%",
    marginBottom: 16,
  },
  textInput: {
    width: "100%",
    height: 50,
    backgroundColor: palette.surfaceElevated,
    borderRadius: 12,
    paddingHorizontal: 16,
    color: palette.textPrimary,
    borderWidth: 1,
    borderColor: palette.border,
    marginBottom: 8,
  },
  suggestionsContainer: {
    width: "100%",
    backgroundColor: palette.surfaceElevated,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderWidth: 1,
    borderColor: palette.border,
    marginTop: 0,
    borderTopWidth: 0,
    maxHeight: 400,
    position: "relative",
    zIndex: 1001,
  },
  suggestionItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "transparent",
  },
  suggestionItemDivider: {
    borderBottomWidth: 1,
    borderBottomColor: palette.border,
  },
  loadingContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: "transparent",
  },
  loadingText: {
    color: palette.textSecondary,
    fontSize: 14,
    marginLeft: 8,
  },
  suggestionContent: {
    flex: 1,
    marginLeft: 8,
  },
  suggestionSubtext: {
    color: palette.textSecondary,
    fontSize: 12,
    marginTop: 2,
  },
  suggestionText: {
    fontSize: 16,
    color: palette.textPrimary,
    marginLeft: 12,
    textAlign: "left",
    flex: 1,
  },
  airlineHeader: {
    marginTop: 16,
    marginBottom: 16,
  },
  airlineName: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
  },

  flightDetailsCard: {
    backgroundColor: palette.surfaceElevated,
    borderRadius: 12,
    padding: 12,
    marginTop: 20,
    borderWidth: 1,
    borderColor: palette.border,
  },
  flightSegmentCard: {
    marginTop: 12,
    marginBottom: 0,
  },
  flightNumberText: {
    fontSize: 14,
    color: palette.textSecondary,
    fontWeight: "400",
    marginBottom: 12,
  },
  flightDetailsTable: {
    gap: 10,
  },
  flightDetailsRowsWrapper: {
    position: "relative",
  },
  flightConnectorLine: {
    position: "absolute",
    left: 8,
    top: "50%",
    height: 22,
    marginTop: -11, // center the line on the midpoint between the two planes
    width: 2,
    backgroundColor: palette.successDeep,
  },
  flightDetailsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    minHeight: 28,
  },
  flightDetailsCellCity: {
    width: 220,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  flightDetailsCellDate: {
    width: 44,
    paddingLeft: 0,
    marginLeft: -18,
    justifyContent: "flex-start",
  },
  flightDetailsCellTime: {
    width: 56,
    paddingLeft: 0,
    paddingRight: 0,
    marginLeft: -6,
    alignItems: "flex-end",
    justifyContent: "center",
  },
  flightDetailsCellArrow: {
    width: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  flightDetailsChevronWrap: {
    position: "absolute",
    right: -6,
    top: "50%",
    width: 24,
    height: 24,
    alignItems: "center",
    justifyContent: "center",
    transform: [{ translateY: -12 }],
  },

  flightCityText: {
    fontSize: 15,
    color: palette.textPrimary,
    fontWeight: "400",
    flex: 1,
    minWidth: 0,
  },

  flightDate: {
    fontSize: 13,
    color: palette.textSecondary,
    fontWeight: "400",
    height: 24,
    lineHeight: 24,
    textAlign: "left",
  },
  flightTime: {
    fontSize: 14,
    color: palette.textPrimary,
    fontWeight: "500",
    height: 24,
    lineHeight: 24,
    textAlign: "right",
  },
  flightActionsContainer: {
    marginTop: 16,
    gap: 12,
  },
  addAnotherFlightButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: palette.successDeep,
    backgroundColor: "transparent",
    gap: 8,
  },
  addAnotherFlightText: {
    fontSize: 16,
    color: palette.successDeep,
    fontWeight: "500",
  },
  continueButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: palette.successDeep,
    alignItems: "center",
    justifyContent: "center",
    alignSelf: "center",
    shadowColor: palette.bg,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  flightInputRow: {
    flexDirection: "row",
    gap: 12,
  },
  flightCarrierInput: {
    flex: 0.4,
  },
  flightNumberInput: {
    flex: 0.6,
  },

  manualEntryButton: {
    paddingVertical: 12,
    alignItems: "center",
    borderBottomWidth: 0,
    borderTopWidth: 0,
  },
  manualEntryButtonText: {
    fontSize: 14,
    color: palette.link,
    fontWeight: "500",
    textDecorationLine: "none",
  },
  dateButton: {
    width: "100%",
    height: 50,
    backgroundColor: palette.surfaceElevated,
    borderRadius: 12,
    paddingHorizontal: 16,
    color: palette.textPrimary,
    borderWidth: 0,
    borderColor: palette.border,
    marginBottom: 16,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateButtonText: {
    fontSize: 16,
    color: palette.textPrimary,
  },

  modalButtonPrimaryText: {
    fontSize: 16,
    fontWeight: "600",
    color: palette.textPrimary,
    textAlign: "center",
  },
  modalButtonsSingleCentered: {
    flexDirection: "row",
    justifyContent: "center",
    width: "100%",
    marginTop: 20,
  },
  primaryCenteredButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: palette.link,
    borderRadius: 12,
    minWidth: 160,
    alignItems: "center",
  },
  locationSearchContainer: {
    marginBottom: 0,
  },
  locationSearchButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: palette.surfaceElevated,
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 0,
    borderColor: palette.border,
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 16,
    color: palette.textPrimary,
    marginRight: 8,
  },

  tapDismissOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    backgroundColor: "transparent",
  },

  vaccinationSection: {
    marginBottom: 20,
  },
});
