import { StyleSheet } from 'react-native';

/** Metric detail modal, overlays, inputs, flight, search, suggestions, chips */
export const travelModalsAndFormsStyles = StyleSheet.create({
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  bottomSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    maxHeight: '80%',
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  modalScrollContent: {
    width: '100%',
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  inputContainer: {
    width: '100%',
    marginBottom: 16,
  },
  textInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#3A3A3C',
    marginBottom: 8,
  },
  suggestionsContainer: {
    width: '100%',
    backgroundColor: '#2C2C2E',
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    borderWidth: 1,
    borderColor: '#3A3A3C',
    marginTop: 0,
    borderTopWidth: 0,
    maxHeight: 400,
    position: 'relative',
    zIndex: 1001,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  suggestionItemDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A3C',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  loadingText: {
    color: '#8E8E93',
    fontSize: 14,
    marginLeft: 8,
  },
  suggestionContent: {
    flex: 1,
    marginLeft: 8,
  },
  suggestionSubtext: {
    color: '#8E8E93',
    fontSize: 12,
    marginTop: 2,
  },
  suggestionText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
    textAlign: 'left',
    flex: 1,
  },
  airlineHeader: {
    marginTop: 16,
    marginBottom: 16,
  },
  airlineName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  combinedFlightInput: {
    width: '100%',
  },
  combinedFlightTextInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  flightDetailsCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#3A3A3C',
    borderBottomWidth: 0,
  },
  flightSegmentCard: {
    marginTop: 12,
    marginBottom: 0,
  },
  flightNumberText: {
    fontSize: 14,
    color: '#8E8E93',
    fontWeight: '400',
    marginBottom: 12,
  },
  flightDetailsTable: {
    gap: 10,
  },
  flightDetailsRowsWrapper: {
    position: 'relative',
  },
  flightDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
  },
  flightDetailsCellCity: {
    width: 220,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  flightDetailsCellDate: {
    width: 44,
    paddingLeft: 0,
    marginLeft: -18,
    justifyContent: 'flex-start',
  },
  flightDetailsCellTime: {
    width: 56,
    paddingLeft: 0,
    paddingRight: 0,
    marginLeft: -6,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  flightDetailsCellArrow: {
    width: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flightDetailsChevronWrap: {
    position: 'absolute',
    right: -6,
    top: '50%',
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -12 }],
  },
  flightDetailsGridScroll: {
    flexGrow: 1,
    paddingRight: 8,
  },
  flightDetailsGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    minWidth: '100%',
  },
  flightDetailsColumnCity: {
    width: 220,
    gap: 10,
    justifyContent: 'center',
  },
  flightDetailsColumnDate: {
    width: 44,
    paddingLeft: 12,
    gap: 10,
    justifyContent: 'center',
  },
  flightDetailsColumnTime: {
    width: 52,
    paddingLeft: 12,
    alignItems: 'flex-end',
    gap: 10,
    justifyContent: 'center',
  },
  flightDetailsColumn: {
    flex: 1,
    gap: 12,
  },
  flightArrowColumn: {
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  flightRouteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 24,
  },
  flightCityText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '400',
    flex: 1,
    minWidth: 0,
  },
  flightCity: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '400',
    flex: 1,
    minWidth: 0,
    flexShrink: 0,
  },
  flightDate: {
    fontSize: 13,
    color: '#8E8E93',
    fontWeight: '400',
    height: 24,
    lineHeight: 24,
    textAlign: 'left',
  },
  flightTime: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
    height: 24,
    lineHeight: 24,
    textAlign: 'right',
  },
  flightActionsContainer: {
    marginTop: 16,
    gap: 12,
  },
  addAnotherFlightButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#059669',
    backgroundColor: 'transparent',
    gap: 8,
  },
  addAnotherFlightText: {
    fontSize: 16,
    color: '#059669',
    fontWeight: '500',
  },
  continueButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#059669',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  flightInputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  flightCarrierInput: {
    flex: 0.4,
  },
  flightNumberInput: {
    flex: 0.6,
  },
  flightInputHint: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 4,
    marginLeft: 4,
  },
  manualEntryButton: {
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 0,
    borderTopWidth: 0,
  },
  manualEntryButtonText: {
    fontSize: 14,
    color: '#3AABF0',
    fontWeight: '500',
    textDecorationLine: 'none',
  },
  dateButton: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    borderWidth: 0,
    borderColor: '#3A3A3C',
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginHorizontal: 8,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#3AABF0',
    textAlign: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: '#3AABF0',
  },
  modalButtonPrimaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  modalButtonsSingleCentered: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginTop: 20,
  },
  primaryCenteredButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#3AABF0',
    borderRadius: 12,
    minWidth: 160,
    alignItems: 'center',
  },
  locationSearchContainer: {
    marginBottom: 0,
  },
  locationSearchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
    marginRight: 8,
  },
  locationSearchText: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
  },
  searchModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  tapDismissOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  searchModalContent: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    alignItems: 'stretch',
    height: 420,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  searchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 16,
  },
  searchTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  searchInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    borderWidth: 0,
    borderColor: '#3A3A3C',
    marginBottom: 16,
  },
  searchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#3AABF0',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  searchButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  locationInfoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  locationInfoContainer: {
    flex: 1,
  },
  locationName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  locationSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 4,
  },
  overallRisk: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  riskText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34C759',
    marginLeft: 8,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  healthcareSection: {
    marginBottom: 20,
  },
  facilityCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  facilityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  facilityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  facilityInfo: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 4,
  },
  facilityDetails: {
    fontSize: 13,
    color: '#8E8E93',
    marginLeft: 16,
  },
  vaccinationSection: {
    marginBottom: 20,
  },
  vaccinationCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  vaccinationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  vaccinationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  vaccineList: {
    marginLeft: 16,
  },
  vaccineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  vaccineText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 8,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  chip: {
    backgroundColor: '#2C2C2E',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  chipActive: {
    backgroundColor: '#3AABF020',
    borderColor: '#3AABF040',
  },
  chipText: {
    color: '#8E8E93',
    fontSize: 12,
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#3AABF0',
  },
});
