import { StyleSheet } from 'react-native';

/** Vaccinations, health summary, metrics, trip cards, jet lag, date pickers, bottom sheet */
export const travelHealthTripsAndSheetsStyles = StyleSheet.create({
  vaccineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  vaccineLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '50%',
  },
  vaccineRight: {
    width: '50%',
    alignItems: 'flex-start',
  },
  vaccineName: {
    flex: 1,
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  vaccineBadge: {
    color: '#8E8E93',
    fontSize: 12,
    marginLeft: 0,
  },
  rowActionBtn: {
    backgroundColor: '#0A84FF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  tipsSection: {
    marginBottom: 20,
  },
  tipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  tipText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 12,
    flex: 1,
  },
  tripProgress: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 12,
  },
  progressItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressText: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  travelHealthHeader: {
    marginBottom: 16,
  },
  travelHealthTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  countryName: {
    fontSize: 18,
    color: '#8E8E93',
  },
  summaryCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  summaryText: {
    fontSize: 14,
    color: '#8E8E93',
  },
  metricsSection: {
    marginBottom: 20,
  },
  metricRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  metricIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2C2C2E',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  metricIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  metricContent: {
    flex: 1,
  },
  
  metricName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  metricValueText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  metricDescriptionText: {
    fontSize: 13,
    color: '#8E8E93',
  },
  metricSeparator: {
    height: 1,
    backgroundColor: '#3A3A3C',
    opacity: 0.3,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  hospitalsSection: {
    marginBottom: 20,
  },
  sectionGroupCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 0,
  },
  hospitalCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  hospitalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  hospitalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  hospitalDistance: {
    fontSize: 13,
    color: '#8E8E93',
    marginLeft: 8,
  },
  hospitalInfo: {
    fontSize: 14,
    color: '#8E8E93',
  },
  medicationSection: {
    marginBottom: 20,
  },
  medicationsSplit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  medCol: {
    width: '48%',
  },
  medColTitle: {
    color: '#8E8E93',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  medicationCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  medPackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#232323',
    borderRadius: 12,
    padding: 14,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#2C2C2E',
    minWidth: 240,
  },
  medPackLeft: {
    gap: 2,
  },
  medPackTitle: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  medPackSubtitle: {
    color: '#8E8E93',
    fontSize: 12,
  },
  medPackRight: {},
  medPackBtn: {
    backgroundColor: '#0A84FF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  medPackBtnText: {
    color: '#fff',
    fontWeight: '600',
  },
  medicationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  medicationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  medGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  medTile: {
    width: '48%',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  medTileText: {
    color: '#FFFFFF',
    fontWeight: '600',
    flex: 1,
    marginLeft: 8,
  },
  medTileTag: {
    color: '#8E8E93',
    fontSize: 12,
    marginLeft: 8,
  },
  medActionBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  medActionBtn: {
    backgroundColor: '#0A84FF',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  medActionText: {
    color: '#fff',
    fontWeight: '600',
  },
  medicationList: {
    marginLeft: 16,
  },
  medicationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  medicationText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 8,
  },
  emergencySection: {
    marginBottom: 20,
  },
  emergencyCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  emergencyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  emergencyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  emergencyDescription: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 4,
  },
  emergencyList: {
    marginLeft: 16,
  },
  emergencyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  emergencyLabel: {
    fontSize: 14,
    color: '#8E8E93',
  },
  emergencyNumber: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  addTripSection: {
    marginBottom: 20,
  },
  tripCardContent: {
    paddingLeft: 20,
    paddingRight: 16,
    paddingTop: 20,
    paddingBottom: 20,
  },
  tripCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  tripCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  tripCardCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2C2C2E',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  tripFlagContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#3A3A3C',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  tripFlag: {
    fontSize: 20,
  },
  tripCardAccent: {
    width: 4,
    height: '100%',
    backgroundColor: '#FF9500',
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
  },
  tripInfo: {
  flex: 1,
},
  tripName: {
    fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
    marginBottom: 2,
  },
  tripDatesSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateItem: {
  flexDirection: 'row',
  alignItems: 'center',
},
  dateText: {
  fontSize: 14,
  color: '#8E8E93',
    marginLeft: 8,
},
  countdownContainer: {
  backgroundColor: '#007AFF',
  borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
},
  countdownText: {
    fontSize: 12,
  color: '#FFFFFF',
  fontWeight: '600',
  },
  jetLagPreview: {
  backgroundColor: '#2C2C2E',
  borderRadius: 8,
  padding: 12,
    marginBottom: 12,
},
jetLagHeader: {
  flexDirection: 'row',
  alignItems: 'center',
    marginBottom: 4,
},
jetLagTitle: {
  fontSize: 14,
  fontWeight: '600',
  color: '#FFFFFF',
  marginLeft: 8,
},
  jetLagInfo: {
    fontSize: 12,
  color: '#8E8E93',
    marginLeft: 24,
},
  tapToView: {
  flexDirection: 'row',
  alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#3A3A3C',
  },
  tapToViewText: {
  fontSize: 14,
    color: '#007AFF',
    marginRight: 8,
  },
  tripDetailsModal: {
  backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxHeight: '80%',
  borderWidth: 1,
    borderColor: '#3A3A3C',
},
  tripDetailsHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 20,
},
  tripDetailsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
  color: '#FFFFFF',
},
  checklistSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  checklistTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 16,
    marginTop: 8,
  },
  checklistSection: {
    marginBottom: 16,
  },
  checklistItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A3C',
  },
  checklistCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#007AFF',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completedCheckbox: {
    backgroundColor: '#007AFF',
  },
  checklistText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  completedText: {
    color: '#8E8E93',
    textDecorationLine: 'line-through',
  },
  datePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
    elevation: 10000,
  },
  datePickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10000,
  },
  datePickerModalContent: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
    zIndex: 10001,
    elevation: 10001,
  },
  datePickerHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
    width: '100%',
    marginBottom: 16,
},
  datePickerCancelText: {
  fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
  },
  datePickerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  color: '#FFFFFF',
  },
  datePickerDoneText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34C759',
  },
  datePicker: {
    width: '100%',
  backgroundColor: '#2C2C2E',
    borderRadius: 12,
  borderWidth: 1,
  borderColor: '#3A3A3C',
    color: '#FFFFFF',
},
  useCurrentLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  useCurrentLocationText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
    marginLeft: 8,
  },
  useCurrentLocationTextDisabled: {
    color: '#8E8E93',
  },
  emptyStateContainer: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  directionsModal: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  modalContentDirections: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    width: '85%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  modalContainerDirections: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    width: '85%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  modalHeaderDirections: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2E',
  },
  modalIconCircleDirections: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#30D15820',
    marginRight: 12,
  },
  modalTitleDirections: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 12,
  },
  hmRangeContainer: {
    alignItems: 'center',
    marginTop: 6,
  },
  directionsModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  directionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  directionsButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  cancelButton: {
    backgroundColor: '#8E8E93',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 12,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  alwaysUseCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  alwaysUseText: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  emergencyModal: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  emergencyModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  emergencyModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 12,
  },
  emergencyCallButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emergencyCallButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  emergencyCancelButton: {
    backgroundColor: '#8E8E93',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emergencyCancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  resultTitleRow: {
    marginBottom: 16,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  tripDestinationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  tripDestinationLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  tripDestinationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF9500',
    marginRight: 12,
    marginTop: 4,
  },
  tripDestinationRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  tripDirectionText: {
    fontSize: 14,
    color: '#FF9500',
    marginTop: 8,
  },
  tripMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  tripMetric: {
    alignItems: 'center',
    flex: 1,
  },
  tripMetricLabel: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 8,
    textAlign: 'center',
  },
  tripMetricValue: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
  },
  sleepScheduleSection: {
    marginBottom: 20,
  },
  sleepScheduleTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  sleepScheduleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  sleepScheduleDate: {
    fontSize: 14,
    color: '#8E8E93',
  },
  sleepScheduleAdjustment: {
    fontSize: 14,
    color: '#34C759',
    fontWeight: '600',
  },
  sleepScheduleMore: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 8,
  },
  sleepSchedulePreview: {
    marginTop: 12,
  },
  sleepScheduleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sleepScheduleDay: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  sleepScheduleTime: {
    fontSize: 12,
    color: '#8E8E93',
  },
  tripActionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF9500',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 16,
  },
  tripActionText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 12,
    fontWeight: '500',
  },
  tripStatusText: {
    fontSize: 12,
    color: '#8E8E93',
    fontWeight: '500',
    marginTop: 4,
  },
  viewMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 12,
    alignSelf: 'center',
  },
  viewMoreButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#007AFF',
    marginLeft: 4,
  },
  tripChecklist: {
    marginTop: 16,
    padding: 16,
  },
  checklistItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  checkbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#007AFF',
    marginRight: 4,
  },
  checkboxCompleted: {
    backgroundColor: '#007AFF',
  },
  checklistItemText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  checklistItemCompleted: {
    color: '#8E8E93',
    textDecorationLine: 'line-through',
  },
  checklistItemStatus: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  jetLagTips: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  jetLagTipsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  jetLagTipsText: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 12,
  },
  journeyTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  journeyTab: {
    flex: 1,
    padding: 8,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    borderRadius: 4,
  },
  journeyTabHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  journeyTabTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 4,
  },
  journeyTabContent: {
    alignItems: 'center',
  },
  journeyDate: {
    fontSize: 14,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  journeyAdjustment: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 4,
  },
  metricRightCol: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  metricScoreText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  metricScoreLabelText: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 2,
  },
  // Bottom Sheet Styles
  bottomSheetContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    zIndex: 1000,
    pointerEvents: 'box-none',
    justifyContent: 'flex-end',
  },
  bottomSheetContent: {
    flex: 1,
    backgroundColor: '#1C1C1E',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    minHeight: '70%',
    maxHeight: '100%',
    paddingBottom: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 16,
  },
  bottomSheetHandleContainer: {
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#3A3A3C',
    borderRadius: 2,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    zIndex: 10,
  },
  bottomSheetCloseButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSheetTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    flex: 1,
  },
  bottomSheetBody: {
    flex: 1,
  },
  bottomSheetBodyContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
});
