import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#000000',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60, // Increased for iPhone 16 Dynamic Island
    paddingBottom: 2,
    backgroundColor: '#000000',
  },
  headerContent: {
    flex: 1,
  },

  headerTitle: {
    fontSize: 28,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  headerSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
    fontWeight: '400',
    lineHeight: 20,
    flexWrap: 'wrap',
  },

  tabContainer: {
    paddingVertical: 16,
    paddingHorizontal: 0,
    backgroundColor: '#000000',
    borderBottomWidth: 1,
    borderBottomColor: '#1C1C1E',
  },
  tabScrollContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    gap: 8,
    justifyContent: 'space-between',
  },
  tab: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    gap: 8,
    borderRadius: 8,
    flex: 1,
  },
  activeTab: {
    borderBottomWidth: 2,
    borderBottomColor: '#007AFF',
  },
  tabText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#8E8E93',
  },
  activeTabText: {
    color: '#007AFF',
    fontWeight: '600',
  },
  scrollContainer: {
    flex: 1,
  },
  pager: {
    flex: 1,
  },
  content: {
    padding: 20,
  },
  contentTrips: {
    paddingTop: 8,
    paddingHorizontal: 4,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  // Detailed modal styles to match dashboard
  modalContainerDetailed: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    width: '100%',
    maxHeight: '90%',
    maxWidth: 420,
    flex: 1,
  },
  modalHeaderDetailed: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 20,
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2E',
  },
  modalIconCircleDetailed: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  modalTitleDetailed: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  modalStatusDetailed: {
    fontSize: 16,
    fontWeight: '600',
    color: '#8E8E93',
  },
  modalSectionDetailed: {
    padding: 20,
    paddingTop: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2E',
  },
  sectionTitleDetailed: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  sectionContentDetailed: {
    fontSize: 15,
    color: '#EBEBF5',
    lineHeight: 22,
  },
  rangeIndicatorContainerDetailed: {
    alignItems: 'center',
    marginTop: 16,
  },
  currentScoreContainerDetailed: {
    marginTop: 16,
    alignItems: 'center',
  },
  currentScoreTextDetailed: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
    marginBottom: 4,
  },
  impactItemDetailed: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  impactTextDetailed: {
    fontSize: 14,
    color: '#EBEBF5',
    marginLeft: 8,
    flex: 1,
    lineHeight: 20,
  },
  recommendationItemDetailed: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  recommendationTextDetailed: {
    fontSize: 14,
    color: '#EBEBF5',
    marginLeft: 8,
    flex: 1,
    lineHeight: 20,
  },
  riskItemDetailed: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  riskTextDetailed: {
    fontSize: 14,
    color: '#EBEBF5',
    marginLeft: 8,
    flex: 1,
    lineHeight: 20,
  },
  description: {
    fontSize: 16,
    color: '#8E8E93',
    lineHeight: 24,
  },
  locationCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 20,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  locationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  locationText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  locationSubtext: {
    fontSize: 14,
    color: '#8E8E93',
  },
  metricsContainer: {
    marginTop: 20,
  },
  metricCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    width: '48%', // Two columns
  },
  metricHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  metricTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  metricValue: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  metricDescription: {
    fontSize: 14,
    color: '#8E8E93',
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 40,
  },
  emptyStateTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginTop: 24,
    marginBottom: 8,
  },
  emptyStateText: {
    fontSize: 16,
    color: '#8E8E93',
    marginTop: 8,
    textAlign: 'center',
    marginBottom: 16,
  },
  tripsContainer: {
    marginTop: 16,
  },
  tripRowWrapper: {
    marginBottom: 12,
  },
  tripRowCompact: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.06)',
  },
  tripRowTextWrap: {
    flex: 1,
  },
  tripRowTitle: {
    fontSize: 17,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  tripRowSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 2,
  },
  tripRowChevron: {
    marginLeft: 8,
  },
  tripRowChevronDown: {
    transform: [{ rotate: '90deg' }],
  },
  tripDetailBlock: {
    marginTop: 12,
    paddingLeft: 0,
  },
  tripAddonToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    alignSelf: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 20,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginBottom: 12,
    borderWidth: 0,
  },
  tripAddonToggleText: {
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  tripAddonsContainer: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    padding: 12,
    marginBottom: 16,
    borderWidth: 0,
  },
  tripTabsRow: {
    flexDirection: 'row',
    gap: 12,
    marginBottom: 12,
    justifyContent: 'center',
  },
  tripTab: {
    color: '#8E8E93',
    fontWeight: '600',
    fontSize: 13,
    backgroundColor: '#2C2C2E',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  tripTabActive: {
    color: '#FFFFFF',
    backgroundColor: '#007AFF20',
  },
  tripChecklistBox: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    borderWidth: 0,
  },
  tripChecklistRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  tripChecklistLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  tripChecklistText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '600',
  },
  tripCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    marginBottom: 20,
  },
  tripCardLarge: {
    backgroundColor: '#1C1C1E',
    borderRadius: 18,
    borderWidth: 0,
    marginBottom: 24,
    padding: 4,
  },
  tripDestinationText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },

  addTripButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 16,
    marginBottom: 8,
  },
  addTripButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  addTripButtonTop: {
    marginTop: 0,
  },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  bottomSheetOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'flex-end',
    alignItems: 'stretch',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    maxHeight: '80%',
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  modalScrollContent: {
    width: '100%',
    marginBottom: 16,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 20,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
    alignSelf: 'flex-start',
  },
  inputContainer: {
    width: '100%',
    marginBottom: 16,
  },
  textInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#3A3A3C',
    marginBottom: 8,
  },
  suggestionsContainer: {
    width: '100%',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    maxHeight: 220,
    overflow: 'hidden',
    position: 'relative',
    zIndex: 1001,
  },
  suggestionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  suggestionItemDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A3C',
  },
  loadingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'transparent',
  },
  loadingText: {
    color: '#8E8E93',
    fontSize: 14,
    marginLeft: 8,
  },
  suggestionContent: {
    flex: 1,
    marginLeft: 8,
  },
  suggestionSubtext: {
    color: '#8E8E93',
    fontSize: 12,
    marginTop: 2,
  },
  suggestionText: {
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
    textAlign: 'left',
    flex: 1,
  },
  airlineHeader: {
    marginTop: 16,
    marginBottom: 16,
  },
  airlineName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  combinedFlightInput: {
    width: '100%',
  },
  combinedFlightTextInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    fontSize: 18,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  flightDetailsCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#3A3A3C',
    borderBottomWidth: 0,
  },
  flightSegmentCard: {
    marginTop: 12,
    marginBottom: 0,
  },
  flightNumberText: {
    fontSize: 14,
    color: '#8E8E93',
    fontWeight: '400',
    marginBottom: 12,
  },
  flightDetailsTable: {
    gap: 10,
  },
  flightDetailsRowsWrapper: {
    position: 'relative',
  },
  flightDetailsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    minHeight: 28,
  },
  flightDetailsCellCity: {
    width: 220,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  flightDetailsCellDate: {
    width: 44,
    paddingLeft: 0,
    marginLeft: -18,
    justifyContent: 'flex-start',
  },
  flightDetailsCellTime: {
    width: 56,
    paddingLeft: 0,
    paddingRight: 0,
    marginLeft: -6,
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  flightDetailsCellArrow: {
    width: 24,
    justifyContent: 'center',
    alignItems: 'center',
  },
  flightDetailsChevronWrap: {
    position: 'absolute',
    right: -6,
    top: '50%',
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
    transform: [{ translateY: -12 }],
  },
  flightDetailsGridScroll: {
    flexGrow: 1,
    paddingRight: 8,
  },
  flightDetailsGrid: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 20,
    minWidth: '100%',
  },
  flightDetailsColumnCity: {
    width: 220,
    gap: 10,
    justifyContent: 'center',
  },
  flightDetailsColumnDate: {
    width: 44,
    paddingLeft: 12,
    gap: 10,
    justifyContent: 'center',
  },
  flightDetailsColumnTime: {
    width: 52,
    paddingLeft: 12,
    alignItems: 'flex-end',
    gap: 10,
    justifyContent: 'center',
  },
  flightDetailsColumn: {
    flex: 1,
    gap: 12,
  },
  flightArrowColumn: {
    width: 20,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 4,
  },
  flightRouteItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    height: 24,
  },
  flightCityText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '400',
    flex: 1,
    minWidth: 0,
  },
  flightCity: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '400',
    flex: 1,
    minWidth: 0,
    flexShrink: 0,
  },
  flightDate: {
    fontSize: 13,
    color: '#8E8E93',
    fontWeight: '400',
    height: 24,
    lineHeight: 24,
    textAlign: 'left',
  },
  flightTime: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
    height: 24,
    lineHeight: 24,
    textAlign: 'right',
  },
  flightActionsContainer: {
    marginTop: 16,
    gap: 12,
  },
  addAnotherFlightButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#059669',
    backgroundColor: 'transparent',
    gap: 8,
  },
  addAnotherFlightText: {
    fontSize: 16,
    color: '#059669',
    fontWeight: '500',
  },
  continueButton: {
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: '#059669',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  flightInputRow: {
    flexDirection: 'row',
    gap: 12,
  },
  flightCarrierInput: {
    flex: 0.4,
  },
  flightNumberInput: {
    flex: 0.6,
  },
  flightInputHint: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 4,
    marginLeft: 4,
  },
  manualEntryButton: {
    paddingVertical: 12,
    alignItems: 'center',
    borderBottomWidth: 0,
    borderTopWidth: 0,
  },
  manualEntryButtonText: {
    fontSize: 14,
    color: '#007AFF',
    fontWeight: '500',
    textDecorationLine: 'none',
  },
  dateButton: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    borderWidth: 0,
    borderColor: '#3A3A3C',
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dateButtonText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  modalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginHorizontal: 8,
  },
  modalButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
    textAlign: 'center',
  },
  modalButtonPrimary: {
    backgroundColor: '#007AFF',
  },
  modalButtonPrimaryText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  modalButtonsSingleCentered: {
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
    marginTop: 20,
  },
  primaryCenteredButton: {
    paddingVertical: 12,
    paddingHorizontal: 24,
    backgroundColor: '#007AFF',
    borderRadius: 12,
    minWidth: 160,
    alignItems: 'center',
  },
  locationSearchContainer: {
    marginBottom: 20,
  },
  locationSearchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  locationSearchInput: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
    marginRight: 8,
  },
  locationSearchText: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
    marginLeft: 12,
  },
  searchModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 999,
  },
  tapDismissOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    backgroundColor: 'transparent',
  },
  searchModalContent: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    alignItems: 'stretch',
    height: 420,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  searchHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: '100%',
    marginBottom: 16,
  },
  searchTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  searchInput: {
    width: '100%',
    height: 50,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingHorizontal: 16,
    color: '#FFFFFF',
    borderWidth: 0,
    borderColor: '#3A3A3C',
    marginBottom: 16,
  },
  searchButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#007AFF',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 10,
  },
  searchButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  locationInfoHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  locationInfoContainer: {
    flex: 1,
  },
  locationName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  locationSubtitle: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 4,
  },
  overallRisk: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  riskText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34C759',
    marginLeft: 8,
  },
  metricsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  healthcareSection: {
    marginBottom: 20,
  },
  facilityCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  facilityHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  facilityTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  facilityInfo: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 4,
  },
  facilityDetails: {
    fontSize: 13,
    color: '#8E8E93',
    marginLeft: 16,
  },
  vaccinationSection: {
    marginBottom: 20,
  },
  vaccinationCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  vaccinationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  vaccinationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  vaccineList: {
    marginLeft: 16,
  },
  vaccineItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  vaccineText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 8,
  },
  chipsRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
    flexWrap: 'wrap',
  },
  chip: {
    backgroundColor: '#2C2C2E',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  chipActive: {
    backgroundColor: '#007AFF20',
    borderColor: '#007AFF40',
  },
  chipText: {
    color: '#8E8E93',
    fontSize: 12,
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#0A84FF',
  },
  vaccineRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    marginBottom: 10,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  vaccineLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    width: '50%',
  },
  vaccineRight: {
    width: '50%',
    alignItems: 'flex-start',
  },
  vaccineName: {
    flex: 1,
    color: '#FFFFFF',
    fontWeight: '600',
    fontSize: 14,
  },
  vaccineBadge: {
    color: '#8E8E93',
    fontSize: 12,
    marginLeft: 0,
  },
  rowActionBtn: {
    backgroundColor: '#0A84FF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 10,
  },
  tipsSection: {
    marginBottom: 20,
  },
  tipCard: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  tipText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 12,
    flex: 1,
  },
  tripProgress: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 12,
  },
  progressItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  progressText: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  travelHealthHeader: {
    marginBottom: 16,
  },
  travelHealthTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  countryName: {
    fontSize: 18,
    color: '#8E8E93',
  },
  summaryCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  summaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  summaryTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  summaryText: {
    fontSize: 14,
    color: '#8E8E93',
  },
  metricsSection: {
    marginBottom: 20,
  },
  metricRowCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  metricIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#2C2C2E',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  metricIconCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  metricContent: {
    flex: 1,
  },
  
  metricName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  metricValueText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#FFFFFF',
    marginBottom: 4,
  },
  metricDescriptionText: {
    fontSize: 13,
    color: '#8E8E93',
  },
  metricSeparator: {
    height: 1,
    backgroundColor: '#3A3A3C',
    opacity: 0.3,
    marginVertical: 8,
    marginHorizontal: 16,
  },
  hospitalsSection: {
    marginBottom: 20,
  },
  sectionGroupCard: {
    backgroundColor: '#1C1C1E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 0,
  },
  hospitalCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  hospitalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  hospitalTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  hospitalDistance: {
    fontSize: 13,
    color: '#8E8E93',
    marginLeft: 8,
  },
  hospitalInfo: {
    fontSize: 14,
    color: '#8E8E93',
  },
  medicationSection: {
    marginBottom: 20,
  },
  medicationsSplit: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  medCol: {
    width: '48%',
  },
  medColTitle: {
    color: '#8E8E93',
    fontSize: 13,
    fontWeight: '600',
    marginBottom: 8,
  },
  medicationCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  medPackCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#232323',
    borderRadius: 12,
    padding: 14,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#2C2C2E',
    minWidth: 240,
  },
  medPackLeft: {
    gap: 2,
  },
  medPackTitle: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  medPackSubtitle: {
    color: '#8E8E93',
    fontSize: 12,
  },
  medPackRight: {},
  medPackBtn: {
    backgroundColor: '#0A84FF',
    borderRadius: 8,
    paddingVertical: 6,
    paddingHorizontal: 12,
  },
  medPackBtnText: {
    color: '#fff',
    fontWeight: '600',
  },
  medicationHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  medicationTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  medGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  medTile: {
    width: '48%',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  medTileText: {
    color: '#FFFFFF',
    fontWeight: '600',
    flex: 1,
    marginLeft: 8,
  },
  medTileTag: {
    color: '#8E8E93',
    fontSize: 12,
    marginLeft: 8,
  },
  medActionBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 12,
  },
  medActionBtn: {
    backgroundColor: '#0A84FF',
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  medActionText: {
    color: '#fff',
    fontWeight: '600',
  },
  medicationList: {
    marginLeft: 16,
  },
  medicationItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  medicationText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 8,
  },
  emergencySection: {
    marginBottom: 20,
  },
  emergencyCard: {
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  emergencyHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
  },
  emergencyTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  emergencyDescription: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 4,
  },
  emergencyList: {
    marginLeft: 16,
  },
  emergencyItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  emergencyLabel: {
    fontSize: 14,
    color: '#8E8E93',
  },
  emergencyNumber: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  addTripSection: {
    marginBottom: 20,
  },
  tripCardContent: {
    paddingLeft: 20,
    paddingRight: 16,
    paddingTop: 20,
    paddingBottom: 20,
  },
  tripCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  tripCardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  tripCardCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2C2C2E',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  tripFlagContainer: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#3A3A3C',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  tripFlag: {
    fontSize: 20,
  },
  tripCardAccent: {
    width: 4,
    height: '100%',
    backgroundColor: '#FF9500',
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
  },
  tripInfo: {
  flex: 1,
},
  tripName: {
    fontSize: 18,
  fontWeight: 'bold',
  color: '#FFFFFF',
    marginBottom: 2,
  },
  tripDatesSection: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  dateItem: {
  flexDirection: 'row',
  alignItems: 'center',
},
  dateText: {
  fontSize: 14,
  color: '#8E8E93',
    marginLeft: 8,
},
  countdownContainer: {
  backgroundColor: '#007AFF',
  borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
},
  countdownText: {
    fontSize: 12,
  color: '#FFFFFF',
  fontWeight: '600',
  },
  jetLagPreview: {
  backgroundColor: '#2C2C2E',
  borderRadius: 8,
  padding: 12,
    marginBottom: 12,
},
jetLagHeader: {
  flexDirection: 'row',
  alignItems: 'center',
    marginBottom: 4,
},
jetLagTitle: {
  fontSize: 14,
  fontWeight: '600',
  color: '#FFFFFF',
  marginLeft: 8,
},
  jetLagInfo: {
    fontSize: 12,
  color: '#8E8E93',
    marginLeft: 24,
},
  tapToView: {
  flexDirection: 'row',
  alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#3A3A3C',
  },
  tapToViewText: {
  fontSize: 14,
    color: '#007AFF',
    marginRight: 8,
  },
  tripDetailsModal: {
  backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxHeight: '80%',
  borderWidth: 1,
    borderColor: '#3A3A3C',
},
  tripDetailsHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginBottom: 20,
},
  tripDetailsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
  color: '#FFFFFF',
},
  checklistSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  checklistTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 16,
    marginTop: 8,
  },
  checklistSection: {
    marginBottom: 16,
  },
  checklistItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#3A3A3C',
  },
  checklistCheckbox: {
    width: 20,
    height: 20,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#007AFF',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  completedCheckbox: {
    backgroundColor: '#007AFF',
  },
  checklistText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  completedText: {
    color: '#8E8E93',
    textDecorationLine: 'line-through',
  },
  datePickerOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 10000,
    elevation: 10000,
  },
  datePickerModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10000,
  },
  datePickerModalContent: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '90%',
    maxWidth: 400,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
    zIndex: 10001,
    elevation: 10001,
  },
  datePickerHeader: {
  flexDirection: 'row',
  justifyContent: 'space-between',
  alignItems: 'center',
    width: '100%',
    marginBottom: 16,
},
  datePickerCancelText: {
  fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
  },
  datePickerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  color: '#FFFFFF',
  },
  datePickerDoneText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#34C759',
  },
  datePicker: {
    width: '100%',
  backgroundColor: '#2C2C2E',
    borderRadius: 12,
  borderWidth: 1,
  borderColor: '#3A3A3C',
    color: '#FFFFFF',
},
  useCurrentLocationButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 16,
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  useCurrentLocationText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#007AFF',
    marginLeft: 8,
  },
  useCurrentLocationTextDisabled: {
    color: '#8E8E93',
  },
  emptyStateContainer: {
    marginTop: 16,
    paddingVertical: 12,
    paddingHorizontal: 20,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  directionsModal: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  modalContentDirections: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    width: '85%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  modalContainerDirections: {
    backgroundColor: '#1C1C1E',
    borderRadius: 20,
    width: '85%',
    maxWidth: 420,
    borderWidth: 1,
    borderColor: '#2C2C2E',
  },
  modalHeaderDirections: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#2C2C2E',
  },
  modalIconCircleDirections: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#30D15820',
    marginRight: 12,
  },
  modalTitleDirections: {
    flex: 1,
    color: '#FFFFFF',
    fontSize: 18,
    fontWeight: '700',
    marginLeft: 12,
  },
  hmRangeContainer: {
    alignItems: 'center',
    marginTop: 6,
  },
  directionsModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  directionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  directionsButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 8,
  },
  cancelButton: {
    backgroundColor: '#8E8E93',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginTop: 12,
  },
  cancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  alwaysUseCheckbox: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 16,
  },
  alwaysUseText: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  emergencyModal: {
    backgroundColor: '#1C1C1E',
    borderRadius: 16,
    padding: 24,
    width: '80%',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#3A3A3C',
  },
  emergencyModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
    marginBottom: 16,
  },
  emergencyModalButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 12,
  },
  emergencyCallButton: {
    backgroundColor: '#FF3B30',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emergencyCallButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  emergencyCancelButton: {
    backgroundColor: '#8E8E93',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
  },
  emergencyCancelButtonText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  resultTitleRow: {
    marginBottom: 16,
  },
  resultTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  tripDestinationRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 24,
  },
  tripDestinationLeft: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  tripDestinationDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#FF9500',
    marginRight: 12,
    marginTop: 4,
  },
  tripDestinationRight: {
    flexDirection: 'column',
    alignItems: 'flex-end',
  },
  tripDirectionText: {
    fontSize: 14,
    color: '#FF9500',
    marginTop: 8,
  },
  tripMetricsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
    paddingHorizontal: 8,
  },
  tripMetric: {
    alignItems: 'center',
    flex: 1,
  },
  tripMetricLabel: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 8,
    textAlign: 'center',
  },
  tripMetricValue: {
    fontSize: 16,
    color: '#FFFFFF',
    fontWeight: '600',
    textAlign: 'center',
  },
  sleepScheduleSection: {
    marginBottom: 20,
  },
  sleepScheduleTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  sleepScheduleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 6,
  },
  sleepScheduleDate: {
    fontSize: 14,
    color: '#8E8E93',
  },
  sleepScheduleAdjustment: {
    fontSize: 14,
    color: '#34C759',
    fontWeight: '600',
  },
  sleepScheduleMore: {
    fontSize: 14,
    color: '#8E8E93',
    marginTop: 8,
  },
  sleepSchedulePreview: {
    marginTop: 12,
  },
  sleepScheduleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sleepScheduleDay: {
    fontSize: 14,
    color: '#FFFFFF',
    fontWeight: '500',
  },
  sleepScheduleTime: {
    fontSize: 12,
    color: '#8E8E93',
  },
  tripActionBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#FF9500',
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    marginTop: 16,
  },
  tripActionText: {
    fontSize: 14,
    color: '#FFFFFF',
    marginLeft: 12,
    fontWeight: '500',
  },
  tripStatusText: {
    fontSize: 12,
    color: '#8E8E93',
    fontWeight: '500',
    marginTop: 4,
  },
  viewMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
    borderRadius: 8,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 12,
    alignSelf: 'center',
  },
  viewMoreButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#007AFF',
    marginLeft: 4,
  },
  tripChecklist: {
    marginTop: 16,
    padding: 16,
  },
  checklistItemLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    marginRight: 8,
  },
  checkbox: {
    width: 16,
    height: 16,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#007AFF',
    marginRight: 4,
  },
  checkboxCompleted: {
    backgroundColor: '#007AFF',
  },
  checklistItemText: {
    fontSize: 16,
    color: '#FFFFFF',
  },
  checklistItemCompleted: {
    color: '#8E8E93',
    textDecorationLine: 'line-through',
  },
  checklistItemStatus: {
    fontSize: 14,
    color: '#8E8E93',
    marginLeft: 8,
  },
  jetLagTips: {
    marginTop: 16,
    padding: 16,
    backgroundColor: '#2C2C2E',
    borderRadius: 12,
    borderWidth: 0,
    borderColor: '#3A3A3C',
  },
  jetLagTipsTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    marginBottom: 8,
  },
  jetLagTipsText: {
    fontSize: 14,
    color: '#8E8E93',
    marginBottom: 12,
  },
  journeyTabs: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  journeyTab: {
    flex: 1,
    padding: 8,
    borderWidth: 0,
    borderColor: '#3A3A3C',
    borderRadius: 4,
  },
  journeyTabHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 4,
  },
  journeyTabTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginLeft: 4,
  },
  journeyTabContent: {
    alignItems: 'center',
  },
  journeyDate: {
    fontSize: 14,
    color: '#FFFFFF',
    marginBottom: 4,
  },
  journeyAdjustment: {
    fontSize: 12,
    color: '#8E8E93',
    marginBottom: 4,
  },
  metricRightCol: {
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  metricScoreText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  metricScoreLabelText: {
    fontSize: 12,
    color: '#8E8E93',
    marginTop: 2,
  },
  // Bottom Sheet Styles
  bottomSheetContainer: {
    position: 'absolute',
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    width: '100%',
    zIndex: 1000,
    pointerEvents: 'box-none',
    justifyContent: 'flex-end',
  },
  bottomSheetContent: {
    flex: 1,
    backgroundColor: '#1C1C1E',
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    width: '100%',
    minHeight: '70%',
    maxHeight: '100%',
    paddingBottom: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.25,
    shadowRadius: 12,
    elevation: 16,
  },
  bottomSheetHandleContainer: {
    paddingVertical: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  bottomSheetHandle: {
    width: 40,
    height: 4,
    backgroundColor: '#3A3A3C',
    borderRadius: 2,
  },
  bottomSheetHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 16,
    zIndex: 10,
  },
  bottomSheetCloseButton: {
    width: 32,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  bottomSheetTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    flex: 1,
  },
  bottomSheetBody: {
    flex: 1,
  },
  bottomSheetBodyContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
  },
  
});
