import { LocationData } from '../../../../../shared/types';
import { useTravelState } from './useTravelState';
import { createTravelHandlers } from './useTravelHandlers';

interface UseTravelScreenParams {
  travelHealth: any;
  getCurrentLocation: () => Promise<any>;
  updateTravelHealthData: (locationData: LocationData) => Promise<void>;
  popularCities: string[];
}

export function useTravelScreen({
  travelHealth,
  getCurrentLocation,
  updateTravelHealthData,
  popularCities,
}: UseTravelScreenParams) {
  const state = useTravelState();

  const {
    resultsOpacity,
    resultsTranslateY,
    tripModalTranslateY,
    inputText, setInputText,
    searchLocation, setSearchLocation,
    selectedLocation, setSelectedLocation,
    citySearchResults, setCitySearchResults,
    filteredCities, setFilteredCities,
    isLoading, setIsLoading,
    showInlineSuggestions, setShowInlineSuggestions,
    apiErrors, setApiErrors,
    isRefreshing, setIsRefreshing,
    isGettingLocation, setIsGettingLocation,
    isLookingUpFlight, setIsLookingUpFlight,
    flightLookupResult, setFlightLookupResult,
    newTripDepartureLocation, setNewTripDepartureLocation,
    newTripDestination, setNewTripDestination,
    newTripDepartureDate, setNewTripDepartureDate,
    showManualEntry, setShowManualEntry,
    trips, setTrips,
    newTripReturnDate, setNewTripReturnDate,
    showAddTripModal, setShowAddTripModal,
    tripSuggestions, setTripSuggestions,
    departureSuggestions, setDepartureSuggestions,
    flightCarrier, setFlightCarrier,
    flightNumber, setFlightNumber,
    detectedAirline, setDetectedAirline,
    flightSegments, setFlightSegments,
    flightDetailsExpanded, setFlightDetailsExpanded,
    editingTrip, setEditingTrip,
    editTripDepartureLocation, setEditTripDepartureLocation,
    editTripDestination, setEditTripDestination,
    editTripDepartureDate, setEditTripDepartureDate,
    editTripReturnDate, setEditTripReturnDate,
    editTripNotes, setEditTripNotes,
    showEditTripModal, setShowEditTripModal,
    editTripSuggestions, setEditTripSuggestions,
    editTripDepartureSuggestions, setEditTripDepartureSuggestions,
    showDatePicker, setShowDatePicker,
    tempDatePickerValue, setTempDatePickerValue, pendingDateRef,
    showEditDatePicker, setShowEditDatePicker,
    tempEditDatePickerValue, setTempEditDatePickerValue,
    showDirectionsModal, setShowDirectionsModal,
    showEmergencyModal, setShowEmergencyModal,
  } = state;

  // contentMeasuredHeight is managed in screen (animation-dependent), pass as dummy for handler creation
  const handlers = createTravelHandlers({
    travelHealth,
    inputText,
    searchLocation,
    selectedLocation,
    citySearchResults,
    popularCities,
    contentMeasuredHeight: 0, // managed in screen
    flightCarrier,
    flightNumber,
    flightLookupResult,
    flightSegments,
    showDatePicker,
    tempDatePickerValue,
    newTripDepartureDate,
    newTripReturnDate,
    newTripDepartureLocation,
    newTripDestination,
    editingTrip,
    editTripDepartureLocation,
    editTripDestination,
    editTripDepartureDate,
    editTripReturnDate,
    editTripNotes,
    showEditDatePicker,
    tempEditDatePickerValue,
    resultsOpacity,
    resultsTranslateY,
    tripModalTranslateY,
    updateTravelHealthData,
    getCurrentLocation,
    setSearchLocation,
    setInputText,
    setFilteredCities,
    setIsLoading,
    setSelectedLocation,
    setCitySearchResults,
    setShowInlineSuggestions,
    setApiErrors,
    setIsRefreshing,
    setIsGettingLocation,
    setIsLookingUpFlight,
    setFlightLookupResult,
    setNewTripDepartureLocation,
    setNewTripDestination,
    setNewTripDepartureDate,
    setShowManualEntry,
    setTrips,
    setNewTripReturnDate,
    setShowAddTripModal,
    setTripSuggestions,
    setDepartureSuggestions,
    setFlightCarrier,
    setFlightNumber,
    setDetectedAirline,
    setFlightSegments,
    setFlightDetailsExpanded,
    setEditingTrip,
    setEditTripDepartureLocation,
    setEditTripDestination,
    setEditTripDepartureDate,
    setEditTripReturnDate,
    setEditTripNotes,
    setShowEditTripModal,
    setEditTripSuggestions,
    setEditTripDepartureSuggestions,
    setShowDatePicker,
    setTempDatePickerValue,
    pendingDateRef,
    setShowEditDatePicker,
    setTempEditDatePickerValue,
    setContentMeasuredHeight: () => {},
    setShowDirectionsModal,
    setShowEmergencyModal,
  });

  return { ...state, ...handlers };
}
