export interface CountryData {
  name: string;
  code: string;
  flag: string;
  idTypes: string[];
  gradient: string[];
}

export const FLAG_IMAGES: Record<string, any> = {
  gb: require("../../../../../../../assets/flags/UK.png"),
  fr: require("../../../../../../../assets/flags/France.png"),
  de: require("../../../../../../../assets/flags/Germany.png"),
  au: require("../../../../../../../assets/flags/Australia.png"),
  ca: require("../../../../../../../assets/flags/Canada.png"),
  us: require("../../../../../../../assets/flags/USA.png"),
  es: require("../../../../../../../assets/flags/Spain.png"),
  it: require("../../../../../../../assets/flags/Italy.png"),
  nl: require("../../../../../../../assets/flags/Netherland.png"),
  se: require("../../../../../../../assets/flags/Sweden.png"),
  no: require("../../../../../../../assets/flags/Norway.png"),
  dk: require("../../../../../../../assets/flags/Denmark.png"),
  ch: require("../../../../../../../assets/flags/Switzerland.png"),
  be: require("../../../../../../../assets/flags/Belgium.png"),
  at: require("../../../../../../../assets/flags/Austria.png"),
  ie: require("../../../../../../../assets/flags/Ireland.png"),
  nz: require("../../../../../../../assets/flags/New Zealand.png"),
  jp: require("../../../../../../../assets/flags/Japan.png"),
  kr: require("../../../../../../../assets/flags/South Korea.png"),
  sg: require("../../../../../../../assets/flags/Singapore.png"),
};

export const COUNTRIES: CountryData[] = [
  {
    name: "United Kingdom",
    code: "GB",
    flag: "🇬🇧",
    idTypes: ["NHS Number", "NI Number"],
    gradient: ["#1e3c72", "#2a5298"],
  },
  {
    name: "France",
    code: "FR",
    flag: "🇫🇷",
    idTypes: ["Carte Vitale", "Numéro de Sécurité Sociale"],
    gradient: ["#667eea", "#764ba2"],
  },
  {
    name: "Germany",
    code: "DE",
    flag: "🇩🇪",
    idTypes: ["Gesundheitskarte", "Versichertennummer"],
    gradient: ["#f093fb", "#f5576c"],
  },
  {
    name: "Australia",
    code: "AU",
    flag: "🇦🇺",
    idTypes: ["Medicare", "DVA Card"],
    gradient: ["#4facfe", "#00f2fe"],
  },
  {
    name: "Canada",
    code: "CA",
    flag: "🇨🇦",
    idTypes: ["Health Card", "SIN"],
    gradient: ["#43e97b", "#38f9d7"],
  },
  {
    name: "United States",
    code: "US",
    flag: "🇺🇸",
    idTypes: ["Medicare", "Medicaid", "SSN"],
    gradient: ["#fa709a", "#fee140"],
  },
  {
    name: "Spain",
    code: "ES",
    flag: "🇪🇸",
    idTypes: ["Tarjeta Sanitaria", "Número de Seguridad Social"],
    gradient: ["#a8edea", "#fed6e3"],
  },
  {
    name: "Italy",
    code: "IT",
    flag: "🇮🇹",
    idTypes: ["Tessera Sanitaria", "Codice Fiscale"],
    gradient: ["#ff9a9e", "#fecfef"],
  },
  {
    name: "Netherlands",
    code: "NL",
    flag: "🇳🇱",
    idTypes: ["DigiD", "BSN"],
    gradient: ["#a18cd1", "#fbc2eb"],
  },
  {
    name: "Sweden",
    code: "SE",
    flag: "🇸🇪",
    idTypes: ["Personnummer", "Folkbokföring"],
    gradient: ["#fad0c4", "#ffd1ff"],
  },
  {
    name: "Norway",
    code: "NO",
    flag: "🇳🇴",
    idTypes: ["Fødselsnummer", "D-nummer"],
    gradient: ["#ffecd2", "#fcb69f"],
  },
  {
    name: "Denmark",
    code: "DK",
    flag: "🇩🇰",
    idTypes: ["CPR-nummer", "NemID"],
    gradient: ["#a8caba", "#5d4e75"],
  },
  {
    name: "Switzerland",
    code: "CH",
    flag: "🇨🇭",
    idTypes: ["AHV-Nummer", "Versichertenkarte"],
    gradient: ["#d299c2", "#fef9d7"],
  },
  {
    name: "Belgium",
    code: "BE",
    flag: "🇧🇪",
    idTypes: ["Mutualité", "Numéro de Registre National"],
    gradient: ["#89f7fe", "#66a6ff"],
  },
  {
    name: "Austria",
    code: "AT",
    flag: "🇦🇹",
    idTypes: ["e-card", "Sozialversicherungsnummer"],
    gradient: ["#fdbb2d", "#22c1c3"],
  },
  {
    name: "Ireland",
    code: "IE",
    flag: "🇮🇪",
    idTypes: ["PPS Number", "Medical Card"],
    gradient: ["#ff9a8b", "#a8e6cf"],
  },
  {
    name: "New Zealand",
    code: "NZ",
    flag: "🇳🇿",
    idTypes: ["NHI Number", "IRD Number"],
    gradient: ["#ffecd2", "#fcb69f"],
  },
  {
    name: "Japan",
    code: "JP",
    flag: "🇯🇵",
    idTypes: ["My Number", "Health Insurance Card"],
    gradient: ["#a8edea", "#fed6e3"],
  },
  {
    name: "South Korea",
    code: "KR",
    flag: "🇰🇷",
    idTypes: ["National Health Insurance", "Resident Registration Number"],
    gradient: ["#d299c2", "#fef9d7"],
  },
  {
    name: "Singapore",
    code: "SG",
    flag: "🇸🇬",
    idTypes: ["NRIC", "Pink IC"],
    gradient: ["#89f7fe", "#66a6ff"],
  },
];
