import React from 'react';
import LegalDocTemplate from './LegalDocTemplate';

const PrivacyPolicyScreen: React.FC = () => (
  <LegalDocTemplate
    title="Privacy Policy"
    content={[
      'Effective Date: 1 January 2025',
      '',
      'This Privacy Policy explains how CoreHealth ("we", "us", "our") collects, uses, discloses, and protects your personal information when you use our mobile application and related services. This policy is designed to comply with the UK General Data Protection Regulation (UK GDPR), the Data Protection Act 2018, and other applicable privacy laws.',
      '',
      '1. INFORMATION WE COLLECT',
      '',
      'Personal Information:',
      '• Name, email address, date of birth, and contact details',
      '• Account credentials and authentication information',
      '• Profile information and preferences',
      '• Device information and app usage analytics',
      '',
      'Health Information:',
      '• Vital signs (heart rate, blood pressure, temperature, oxygen saturation)',
      '• Laboratory results and medical test data',
      '• Medications, dosages, and treatment schedules',
      '• Symptoms, health observations, and medical history',
      '• Sleep patterns, activity levels, and fitness data',
      '• Emergency contact information and medical alerts',
      '• Family medical history and genetic information',
      '',
      '2. HOW WE USE YOUR INFORMATION',
      '',
      'We use your information for the following purposes:',
      '• Providing personalized health tracking and insights',
      '• Sending health reminders, medication alerts, and notifications',
      '• Enabling data synchronization across your devices',
      '• Improving app functionality and user experience',
      '• Providing customer support and technical assistance',
      '• Complying with legal obligations and regulatory requirements',
      '• Conducting research and development (using anonymized data only)',
      '',
      'We do NOT use your health data for advertising, marketing, or commercial purposes unrelated to your health.',
      '',
      '3. LEGAL BASIS FOR PROCESSING (UK GDPR)',
      '',
      'We process your personal data based on the following legal grounds:',
      '• Consent: When you explicitly agree to data processing',
      '• Contract Performance: To provide the services you requested',
      '• Legitimate Interests: For security, fraud prevention, and service improvement',
      '• Legal Obligations: To comply with applicable laws and regulations',
      '• Vital Interests: To protect your health and safety in emergencies',
      '',
      '4. DATA SECURITY AND PROTECTION',
      '',
      'Your health data security is our highest priority:',
      '• End-to-end encryption for all data in transit and at rest',
      '• HIPAA-compliant data storage and transmission protocols',
      '• Multi-factor authentication and secure access controls',
      '• Regular security audits, penetration testing, and vulnerability assessments',
      '• Zero-knowledge architecture - we cannot access your unencrypted health data',
      '• Role-based access controls and comprehensive audit logging',
      '• Regular security training for all staff and contractors',
      '',
      '5. DATA SHARING AND DISCLOSURE',
      '',
      'We do NOT sell, rent, or trade your personal or health information. We may share data only in these limited circumstances:',
      '',
      'With Your Explicit Consent:',
      '• Healthcare providers you authorize',
      '• Family members or caregivers you designate',
      '• Third-party health applications you connect',
      '• Research institutions (using anonymized data only)',
      '',
      'For Safety and Legal Compliance:',
      '• Emergency contacts during medical emergencies',
      '• Healthcare professionals when required by law',
      '• Regulatory authorities for compliance purposes',
      '• Law enforcement when required by court order',
      '',
      'Service Providers:',
      '• Cloud storage providers under strict data processing agreements',
      '• Analytics services using anonymized data only',
      '• Customer support tools with limited access',
      '',
      '6. INTERNATIONAL DATA TRANSFERS',
      '',
      'If your data is transferred outside the UK or European Economic Area (EEA), we ensure adequate protection through:',
      '• Standard Contractual Clauses (SCCs) approved by the UK Information Commissioner',
      '• Adequacy decisions by the UK government',
      '• Binding corporate rules for multinational transfers',
      '• Other appropriate safeguards as required by UK GDPR',
      '',
      '7. YOUR RIGHTS UNDER UK GDPR',
      '',
      'You have the following rights regarding your personal data:',
      '• Right of Access: Request a copy of your personal data',
      '• Right to Rectification: Correct inaccurate or incomplete data',
      '• Right to Erasure: Request deletion of your personal data',
      '• Right to Restrict Processing: Limit how we use your data',
      '• Right to Data Portability: Receive your data in a portable format',
      '• Right to Object: Object to processing based on legitimate interests',
      '• Right to Withdraw Consent: Withdraw consent at any time',
      '• Right to Lodge a Complaint: Complain to the Information Commissioner\'s Office (ICO)',
      '',
      '8. DATA RETENTION',
      '',
      'We retain your personal data only as long as necessary to:',
      '• Provide the services you requested',
      '• Comply with legal and regulatory obligations',
      '• Resolve disputes and enforce agreements',
      '• Maintain security and prevent fraud',
      '',
      'Health data is typically retained for 7 years from your last activity, unless you request deletion earlier. Anonymized data may be retained indefinitely for research purposes.',
      '',
      '9. CHILDREN\'S PRIVACY',
      '',
      'Our services are not intended for children under 16 years of age. We do not knowingly collect personal information from children under 16. If you believe we have collected information from a child under 16, please contact us immediately.',
      '',
      '10. COOKIES AND TRACKING TECHNOLOGIES',
      '',
      'Our app uses limited tracking technologies for:',
      '• Essential functionality and security',
      '• Performance monitoring and crash diagnostics',
      '• Analytics to improve user experience (anonymized only)',
      '',
      'We do NOT use third-party advertising or tracking cookies that process your health data.',
      '',
      '11. DATA BREACH NOTIFICATION',
      '',
      'In the event of a data breach that poses a risk to your rights and freedoms, we will:',
      '• Notify the Information Commissioner\'s Office within 72 hours',
      '• Notify affected users without undue delay',
      '• Provide detailed information about the breach and mitigation steps',
      '• Cooperate fully with regulatory investigations',
      '',
      '12. CHANGES TO THIS PRIVACY POLICY',
      '',
      'We may update this Privacy Policy periodically to reflect changes in our practices or applicable laws. We will notify you of material changes through:',
      '• In-app notifications',
      '• Email communications',
      '• Updates to our website',
      '',
      'Continued use of our services after changes become effective indicates acceptance of the updated policy.',
      '',
      '13. CONTACT INFORMATION',
      '',
      'For privacy-related questions, concerns, or to exercise your rights:',
      '',
      'Data Protection Officer:',
      'Email: dpo@corehealth.app',
      'Phone: +44 (0) 20 7123 4567',
      '',
      'Privacy Team:',
      'Email: privacy@corehealth.app',
      'Address: CoreHealth Ltd, 123 Health Street, London, EC1A 1BB, United Kingdom',
      '',
      'Information Commissioner\'s Office:',
      'Website: https://ico.org.uk',
      'Phone: 0303 123 1113',
      '',
      '14. COMPLIANCE AND CERTIFICATIONS',
      '',
      'CoreHealth maintains the following compliance certifications:',
      '• UK GDPR compliance',
      '• ISO 27001 Information Security Management',
      '• SOC 2 Type II Security and Privacy',
      '• HIPAA compliance for US healthcare data',
      '• NHS Digital Data Security and Protection Toolkit',
      '',
      'We regularly review and update our privacy practices to ensure ongoing compliance with evolving regulations and best practices.',
    ]}
  />
);

export default PrivacyPolicyScreen; 