import OpenAI from 'openai';

/**
 * All tool definitions for the Toto AI agent.
 * Each tool maps 1:1 to a case in executor.ts.
 */
export const TOTO_TOOLS: OpenAI.Chat.Completions.ChatCompletionTool[] = [
  // VACCINATIONS
  { type: 'function', function: { name: 'create_vaccination', description: 'Record a new vaccination the user has received', parameters: { type: 'object', properties: { name: { type: 'string', description: 'Vaccine name e.g. COVID-19, Flu, Hepatitis A' }, date: { type: 'string', description: 'Date received YYYY-MM-DD' }, nextDue: { type: 'string', description: 'Next due date YYYY-MM-DD' }, location: { type: 'string' }, batchNumber: { type: 'string' }, notes: { type: 'string' } }, required: ['name', 'date'] } } },
  { type: 'function', function: { name: 'update_vaccination', description: 'Edit an existing vaccination record', parameters: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, date: { type: 'string', description: 'YYYY-MM-DD' }, nextDue: { type: 'string', description: 'YYYY-MM-DD' }, location: { type: 'string' }, batchNumber: { type: 'string' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_vaccination', description: 'Remove a vaccination record', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // MEDICATIONS
  { type: 'function', function: { name: 'create_medication', description: 'Add a new medication the user is taking', parameters: { type: 'object', properties: { name: { type: 'string' }, dosage: { type: 'string', description: 'e.g. 10mg' }, frequency: { type: 'string', description: 'e.g. once daily' }, startDate: { type: 'string', description: 'YYYY-MM-DD' }, notes: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'update_medication', description: 'Update an existing medication', parameters: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, dosage: { type: 'string' }, frequency: { type: 'string' }, endDate: { type: 'string', description: 'YYYY-MM-DD — set if the user stopped taking it' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_medication', description: 'Remove a medication record', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // MEDICAL CONDITIONS
  { type: 'function', function: { name: 'create_condition', description: 'Add a new medical condition or diagnosis', parameters: { type: 'object', properties: { name: { type: 'string' }, severity: { type: 'string', enum: ['mild', 'moderate', 'severe'] }, diagnosedDate: { type: 'string', description: 'YYYY-MM-DD' }, status: { type: 'string', enum: ['active', 'managed', 'resolved'] }, notes: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'update_condition', description: 'Update a medical condition e.g. mark as resolved', parameters: { type: 'object', properties: { id: { type: 'string' }, severity: { type: 'string', enum: ['mild', 'moderate', 'severe'] }, status: { type: 'string', enum: ['active', 'managed', 'resolved'] }, resolvedDate: { type: 'string', description: 'YYYY-MM-DD' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_condition', description: 'Remove a medical condition record', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // APPOINTMENTS
  { type: 'function', function: { name: 'create_appointment', description: 'Add a new medical appointment to the timeline', parameters: { type: 'object', properties: { title: { type: 'string', description: 'Appointment title e.g. GP Check-up, Blood Test' }, eventDate: { type: 'string', description: 'ISO date string YYYY-MM-DDTHH:MM:SS' }, subtitle: { type: 'string', description: 'Short description or appointment type' }, doctor: { type: 'string' }, location: { type: 'string' }, notes: { type: 'string' } }, required: ['title', 'eventDate'] } } },
  { type: 'function', function: { name: 'update_appointment', description: 'Update an existing appointment', parameters: { type: 'object', properties: { id: { type: 'string' }, title: { type: 'string' }, subtitle: { type: 'string' }, eventDate: { type: 'string' }, doctor: { type: 'string' }, location: { type: 'string' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_appointment', description: 'Delete an appointment from the timeline', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // ALLERGIES
  { type: 'function', function: { name: 'create_allergy', description: 'Record a new allergy', parameters: { type: 'object', properties: { name: { type: 'string' }, severity: { type: 'string', enum: ['mild', 'moderate', 'severe', 'life_threatening'] }, reaction: { type: 'string', description: 'Description of the reaction' }, notes: { type: 'string' } }, required: ['name', 'severity'] } } },
  { type: 'function', function: { name: 'update_allergy', description: 'Edit an existing allergy record', parameters: { type: 'object', properties: { id: { type: 'string' }, name: { type: 'string' }, severity: { type: 'string', enum: ['mild', 'moderate', 'severe', 'life_threatening'] }, reaction: { type: 'string' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'resolve_allergy', description: 'Mark an allergy as resolved / no longer active', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // TRIPS
  { type: 'function', function: { name: 'create_trip', description: 'Add a planned trip', parameters: { type: 'object', properties: { departureLocation: { type: 'string' }, destination: { type: 'string' }, departureDate: { type: 'string', description: 'YYYY-MM-DDTHH:MM:SS' }, returnDate: { type: 'string', description: 'YYYY-MM-DDTHH:MM:SS' }, timezone: { type: 'string' }, notes: { type: 'string' } }, required: ['departureLocation', 'destination', 'departureDate'] } } },
  { type: 'function', function: { name: 'update_trip', description: 'Update an existing trip', parameters: { type: 'object', properties: { id: { type: 'string' }, departureLocation: { type: 'string' }, destination: { type: 'string' }, departureDate: { type: 'string' }, returnDate: { type: 'string' }, timezone: { type: 'string' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_trip', description: 'Remove a planned trip', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // SYMPTOMS
  { type: 'function', function: { name: 'log_symptom', description: 'Log a symptom the user is experiencing', parameters: { type: 'object', properties: { type: { type: 'string', enum: ['physical', 'mental'] }, category: { type: 'string', description: 'e.g. headache, fatigue, anxiety, chest pain' }, severity: { type: 'number', description: '1–10 scale' }, duration: { type: 'string', description: 'e.g. 2 hours, since yesterday' }, location: { type: 'string', description: 'Body location if physical' }, notes: { type: 'string' }, factors: { type: 'array', items: { type: 'string' }, description: 'Possible contributing factors' }, loggedAt: { type: 'string', description: 'ISO date, defaults to now' } }, required: ['type', 'category', 'severity'] } } },
  { type: 'function', function: { name: 'delete_symptom', description: 'Remove a logged symptom entry', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },

  // PROFILE DATA — blood type & lifestyle
  { type: 'function', function: { name: 'update_blood_type', description: 'Set or update the user\'s blood type', parameters: { type: 'object', properties: { bloodType: { type: 'string', description: 'e.g. A+, B-, O+, AB+' } }, required: ['bloodType'] } } },
  { type: 'function', function: { name: 'update_lifestyle', description: 'Update lifestyle information: smoking, alcohol, diet, exercise, sleep, stress', parameters: { type: 'object', properties: { smoking: { type: 'object', properties: { status: { type: 'string', enum: ['never', 'former', 'current'] }, packYears: { type: 'number' }, quitDate: { type: 'string' } } }, alcohol: { type: 'object', properties: { frequency: { type: 'string' }, unitsPerWeek: { type: 'number' } } }, diet: { type: 'object', properties: { type: { type: 'string' }, restrictions: { type: 'array', items: { type: 'string' } }, supplements: { type: 'array', items: { type: 'string' } } } }, exercise: { type: 'object', properties: { frequency: { type: 'string' }, type: { type: 'array', items: { type: 'string' } }, intensity: { type: 'string' } } }, sleep: { type: 'object', properties: { averageHoursPerNight: { type: 'number' }, sleepQuality: { type: 'string' }, sleepDisorders: { type: 'array', items: { type: 'string' } } } }, stress: { type: 'object', properties: { level: { type: 'string', enum: ['low', 'moderate', 'high'] }, managementTechniques: { type: 'array', items: { type: 'string' } } } } }, required: [] } } },

  // PROFILE DATA — health IDs
  { type: 'function', function: { name: 'add_health_id', description: 'Add a health/national ID (NHS number, social security health number, etc.)', parameters: { type: 'object', properties: { idType: { type: 'string', description: 'e.g. NHS, Social Security, Medicare' }, country: { type: 'string', description: '2-letter country code' }, idNumber: { type: 'string' }, isPrimary: { type: 'boolean' }, notes: { type: 'string' } }, required: ['idType', 'idNumber'] } } },
  { type: 'function', function: { name: 'update_health_id', description: 'Update an existing health ID', parameters: { type: 'object', properties: { _id: { type: 'string' }, idType: { type: 'string' }, country: { type: 'string' }, idNumber: { type: 'string' }, isPrimary: { type: 'boolean' }, notes: { type: 'string' } }, required: ['_id'] } } },
  { type: 'function', function: { name: 'delete_health_id', description: 'Remove a health ID', parameters: { type: 'object', properties: { _id: { type: 'string' } }, required: ['_id'] } } },

  // PROFILE DATA — emergency contacts
  { type: 'function', function: { name: 'add_emergency_contact', description: 'Add an emergency contact', parameters: { type: 'object', properties: { name: { type: 'string' }, relationship: { type: 'string' }, phone: { type: 'string' }, email: { type: 'string' }, isPrimary: { type: 'boolean' } }, required: ['name', 'phone'] } } },
  { type: 'function', function: { name: 'update_emergency_contact', description: 'Update an existing emergency contact', parameters: { type: 'object', properties: { _id: { type: 'string' }, name: { type: 'string' }, relationship: { type: 'string' }, phone: { type: 'string' }, email: { type: 'string' }, isPrimary: { type: 'boolean' } }, required: ['_id'] } } },
  { type: 'function', function: { name: 'delete_emergency_contact', description: 'Remove an emergency contact', parameters: { type: 'object', properties: { _id: { type: 'string' } }, required: ['_id'] } } },

  // PROFILE DATA — doctors
  { type: 'function', function: { name: 'add_doctor', description: 'Add a doctor or specialist', parameters: { type: 'object', properties: { name: { type: 'string' }, specialty: { type: 'string', description: 'e.g. GP, Cardiologist, Endocrinologist' }, phone: { type: 'string' }, office: { type: 'string' }, email: { type: 'string' }, isPrimary: { type: 'boolean', description: 'Set true to make this the primary doctor' } }, required: ['name', 'specialty'] } } },
  { type: 'function', function: { name: 'update_doctor', description: 'Update a doctor\'s info', parameters: { type: 'object', properties: { _id: { type: 'string' }, name: { type: 'string' }, specialty: { type: 'string' }, phone: { type: 'string' }, office: { type: 'string' }, email: { type: 'string' }, isPrimary: { type: 'boolean' } }, required: ['_id'] } } },
  { type: 'function', function: { name: 'delete_doctor', description: 'Remove a doctor', parameters: { type: 'object', properties: { _id: { type: 'string' } }, required: ['_id'] } } },

  // PROFILE DATA — screenings
  { type: 'function', function: { name: 'add_screening', description: 'Add a health screening result', parameters: { type: 'object', properties: { name: { type: 'string', description: 'e.g. Colonoscopy, Mammogram, PSA Test' }, date: { type: 'string', description: 'YYYY-MM-DD' }, result: { type: 'string' }, nextDue: { type: 'string', description: 'YYYY-MM-DD' }, notes: { type: 'string' } }, required: ['name'] } } },
  { type: 'function', function: { name: 'update_screening', description: 'Update an existing screening record', parameters: { type: 'object', properties: { _id: { type: 'string' }, name: { type: 'string' }, date: { type: 'string' }, result: { type: 'string' }, nextDue: { type: 'string' }, notes: { type: 'string' } }, required: ['_id'] } } },
  { type: 'function', function: { name: 'delete_screening', description: 'Remove a screening record', parameters: { type: 'object', properties: { _id: { type: 'string' } }, required: ['_id'] } } },

  // PROFILE DATA — family history
  { type: 'function', function: { name: 'add_family_history', description: 'Add a family history condition', parameters: { type: 'object', properties: { relation: { type: 'string', description: 'e.g. father, mother, paternal grandfather' }, condition: { type: 'string', description: 'Medical condition name' }, ageOfOnset: { type: 'number' }, notes: { type: 'string' } }, required: ['relation', 'condition'] } } },
  { type: 'function', function: { name: 'delete_family_history', description: 'Remove a family history entry', parameters: { type: 'object', properties: { _id: { type: 'string' } }, required: ['_id'] } } },

  // BIOMARKERS
  { type: 'function', function: { name: 'add_biomarker', description: 'Record a new biomarker value the user has shared e.g. cholesterol, blood pressure, HbA1c', parameters: { type: 'object', properties: { name: { type: 'string', description: 'Biomarker name e.g. Total Cholesterol, HbA1c, Vitamin D' }, value: { type: 'number' }, unit: { type: 'string', description: 'e.g. mmol/L, %, ng/mL' }, category: { type: 'string', enum: ['cardiovascular', 'metabolic', 'hormonal', 'inflammatory', 'nutritional', 'other'] }, recordedAt: { type: 'string', description: 'ISO date, defaults to now' } }, required: ['name', 'value', 'unit', 'category'] } } },
  { type: 'function', function: { name: 'update_biomarker', description: 'Correct a biomarker entry — use when the user says a value was wrong (e.g. misread decimal, wrong unit)', parameters: { type: 'object', properties: { id: { type: 'string', description: 'Biomarker record id shown as [id:xxx] in the data' }, value: { type: 'number' }, unit: { type: 'string' }, category: { type: 'string', enum: ['cardiovascular', 'metabolic', 'hormonal', 'inflammatory', 'nutritional', 'other'] } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_biomarker', description: 'Remove an incorrect or duplicate biomarker entry', parameters: { type: 'object', properties: { id: { type: 'string', description: 'Biomarker record id shown as [id:xxx] in the data' } }, required: ['id'] } } },

  // IMAGING / SCANS
  { type: 'function', function: { name: 'add_imaging_result', description: 'Store a radiology or imaging study result (X-ray, MRI, CT, ultrasound, ECG, DEXA, endoscopy, etc.) from a report or document', parameters: { type: 'object', properties: { modality: { type: 'string', enum: ['x-ray', 'mri', 'ct', 'ultrasound', 'pet', 'dexa', 'ecg', 'echo', 'endoscopy', 'other'], description: 'Type of imaging study' }, bodyPart: { type: 'string', description: 'Body area imaged e.g. chest, abdomen, left knee, brain' }, studyDate: { type: 'string', description: 'Date of the study YYYY-MM-DD' }, facility: { type: 'string', description: 'Hospital or clinic name' }, radiologist: { type: 'string', description: 'Reporting doctor name' }, findings: { type: 'string', description: 'Full findings text from the report' }, impression: { type: 'string', description: 'Conclusion / impression / summary from the report' }, measurements: { type: 'object', description: 'Key measurements as key:value pairs e.g. {"liver_size_cm": 13.2, "t_score": -1.8}' }, notes: { type: 'string' } }, required: ['modality'] } } },
  { type: 'function', function: { name: 'update_imaging_result', description: 'Edit an existing imaging result — correct findings, impression, measurements, or metadata', parameters: { type: 'object', properties: { id: { type: 'string' }, modality: { type: 'string', enum: ['x-ray', 'mri', 'ct', 'ultrasound', 'pet', 'dexa', 'ecg', 'echo', 'endoscopy', 'other'] }, bodyPart: { type: 'string' }, studyDate: { type: 'string' }, facility: { type: 'string' }, radiologist: { type: 'string' }, findings: { type: 'string' }, impression: { type: 'string' }, measurements: { type: 'object' }, notes: { type: 'string' } }, required: ['id'] } } },
  { type: 'function', function: { name: 'delete_imaging_result', description: 'Remove an imaging result', parameters: { type: 'object', properties: { id: { type: 'string' } }, required: ['id'] } } },
];
