export type Circle = { id: string; name: string; members: number; icon: string; color: string };
export const ALL_CIRCLES: Circle[] = [
  { id: 'c1', name: 'Family',            members: 5,  icon: 'home',       color: '#5856D6' },
  { id: 'c2', name: 'Friends',           members: 8,  icon: 'people',     color: '#5856D6' },
  { id: 'c3', name: 'Hikes and Parties', members: 42, icon: 'trail-sign', color: '#5856D6' },
  { id: 'c4', name: 'Football Paris',    members: 18, icon: 'football',   color: '#5856D6' },
  { id: 'c5', name: 'Wellness Warriors', members: 12, icon: 'fitness',    color: '#5856D6' },
  { id: 'c6', name: 'Weekend Runners',   members: 9,  icon: 'walk',       color: '#5856D6' },
];

export type League = { id: string; name: string; members: number; category: string };
export const ALL_LEAGUES: League[] = [
  { id: 'rl1',  name: 'UK · Men 20–30',            members: 128, category: 'Regional'  },
  { id: 'rl3',  name: 'Football · Recovery Circle', members: 96,  category: 'Sport'     },
  { id: 'rl4',  name: 'Entrepreneurs Anti‑Stress',  members: 173, category: 'Lifestyle' },
  { id: 'rl5',  name: 'Paris · Women 30–40',        members: 88,  category: 'Regional'  },
  { id: 'rl6',  name: 'NYC · High Performers',      members: 142, category: 'Regional'  },
  { id: 'rl7',  name: 'Mindful Mornings',           members: 121, category: 'Lifestyle' },
  { id: 'rl8',  name: 'Longevity Pros',             members: 110, category: 'Health'    },
  { id: 'rl9',  name: 'Sleep Optimizers',           members: 97,  category: 'Health'    },
  { id: 'rl10', name: 'Mediterranean Health',       members: 104, category: 'Regional'  },
];

export const flagFromCode = (code: string) => {
  const u = code.toUpperCase();
  const b = 0x1f1e6;
  return String.fromCodePoint(u.charCodeAt(0) - 65 + b, u.charCodeAt(1) - 65 + b);
};

export type Country = { name: string; code: string; score: number; delta: number };
export const COUNTRIES: Country[] = [
  { name: 'Japan',          code: 'JP', score: 84.4, delta:  1 },
  { name: 'Switzerland',    code: 'CH', score: 83.7, delta:  0 },
  { name: 'Singapore',      code: 'SG', score: 83.5, delta: -1 },
  { name: 'Spain',          code: 'ES', score: 83.5, delta:  1 },
  { name: 'South Korea',    code: 'KR', score: 83.2, delta:  0 },
  { name: 'Italy',          code: 'IT', score: 83.2, delta: -1 },
  { name: 'Sweden',         code: 'SE', score: 83.0, delta:  1 },
  { name: 'Norway',         code: 'NO', score: 82.9, delta:  0 },
  { name: 'Australia',      code: 'AU', score: 82.9, delta: -1 },
  { name: 'Israel',         code: 'IL', score: 82.8, delta:  1 },
  { name: 'France',         code: 'FR', score: 82.6, delta:  0 },
  { name: 'Iceland',        code: 'IS', score: 82.6, delta: -1 },
  { name: 'Canada',         code: 'CA', score: 82.0, delta:  1 },
  { name: 'Netherlands',    code: 'NL', score: 82.0, delta:  0 },
  { name: 'Greece',         code: 'GR', score: 81.9, delta: -1 },
  { name: 'Austria',        code: 'AT', score: 81.8, delta:  1 },
  { name: 'Finland',        code: 'FI', score: 81.8, delta:  0 },
  { name: 'Belgium',        code: 'BE', score: 81.7, delta: -1 },
  { name: 'New Zealand',    code: 'NZ', score: 81.7, delta:  1 },
  { name: 'United Kingdom', code: 'GB', score: 81.2, delta:  0 },
  { name: 'Denmark',        code: 'DK', score: 81.2, delta: -1 },
  { name: 'Germany',        code: 'DE', score: 81.0, delta:  1 },
  { name: 'Portugal',       code: 'PT', score: 80.9, delta:  0 },
  { name: 'Luxembourg',     code: 'LU', score: 80.7, delta: -1 },
  { name: 'Ireland',        code: 'IE', score: 80.6, delta:  1 },
  { name: 'Malta',          code: 'MT', score: 80.5, delta:  0 },
  { name: 'Slovenia',       code: 'SI', score: 80.2, delta: -1 },
  { name: 'Cyprus',         code: 'CY', score: 80.1, delta:  1 },
  { name: 'United States',  code: 'US', score: 78.5, delta: -1 },
  { name: 'Czech Republic', code: 'CZ', score: 78.3, delta:  0 },
  { name: 'Poland',         code: 'PL', score: 77.8, delta:  1 },
  { name: 'Chile',          code: 'CL', score: 77.6, delta:  0 },
  { name: 'Costa Rica',     code: 'CR', score: 77.5, delta: -1 },
  { name: 'Cuba',           code: 'CU', score: 77.4, delta:  1 },
  { name: 'Croatia',        code: 'HR', score: 77.2, delta:  0 },
  { name: 'China',          code: 'CN', score: 77.1, delta: -1 },
  { name: 'Slovakia',       code: 'SK', score: 76.9, delta:  1 },
  { name: 'Estonia',        code: 'EE', score: 76.8, delta:  0 },
  { name: 'Lithuania',      code: 'LT', score: 76.4, delta: -1 },
  { name: 'Argentina',      code: 'AR', score: 76.3, delta:  1 },
  { name: 'Panama',         code: 'PA', score: 76.2, delta:  0 },
  { name: 'Uruguay',        code: 'UY', score: 76.1, delta: -1 },
  { name: 'Latvia',         code: 'LV', score: 75.5, delta:  1 },
  { name: 'Brazil',         code: 'BR', score: 75.9, delta:  0 },
  { name: 'Hungary',        code: 'HU', score: 75.4, delta: -1 },
  { name: 'Serbia',         code: 'RS', score: 75.2, delta:  1 },
  { name: 'Thailand',       code: 'TH', score: 75.0, delta:  0 },
  { name: 'Mexico',         code: 'MX', score: 74.8, delta: -1 },
  { name: 'Malaysia',       code: 'MY', score: 74.7, delta:  1 },
  { name: 'Colombia',       code: 'CO', score: 74.5, delta:  0 },
  { name: 'Vietnam',        code: 'VN', score: 74.3, delta: -1 },
  { name: 'Albania',        code: 'AL', score: 74.1, delta:  1 },
  { name: 'Ecuador',        code: 'EC', score: 73.8, delta:  0 },
  { name: 'Sri Lanka',      code: 'LK', score: 73.6, delta: -1 },
  { name: 'Turkey',         code: 'TR', score: 73.0, delta:  1 },
  { name: 'Peru',           code: 'PE', score: 72.8, delta:  0 },
  { name: 'Jamaica',        code: 'JM', score: 72.6, delta: -1 },
  { name: 'Dominican Rep.', code: 'DO', score: 72.4, delta:  1 },
  { name: 'Iran',           code: 'IR', score: 72.2, delta:  0 },
  { name: 'UAE',            code: 'AE', score: 72.0, delta: -1 },
  { name: 'Jordan',         code: 'JO', score: 71.8, delta:  1 },
  { name: 'Paraguay',       code: 'PY', score: 71.5, delta:  0 },
  { name: 'Tunisia',        code: 'TN', score: 71.3, delta: -1 },
  { name: 'Morocco',        code: 'MA', score: 71.1, delta:  1 },
  { name: 'Bolivia',        code: 'BO', score: 70.9, delta:  0 },
  { name: 'India',          code: 'IN', score: 70.4, delta: -1 },
  { name: 'Egypt',          code: 'EG', score: 70.2, delta:  1 },
  { name: 'Philippines',    code: 'PH', score: 70.1, delta:  0 },
  { name: 'Indonesia',      code: 'ID', score: 69.8, delta: -1 },
  { name: 'Mongolia',       code: 'MN', score: 69.5, delta:  1 },
  { name: 'Ukraine',        code: 'UA', score: 69.2, delta:  0 },
  { name: 'Russia',         code: 'RU', score: 68.9, delta: -1 },
  { name: 'Kazakhstan',     code: 'KZ', score: 68.7, delta:  1 },
  { name: 'Algeria',        code: 'DZ', score: 68.5, delta:  0 },
  { name: 'Bangladesh',     code: 'BD', score: 67.9, delta: -1 },
  { name: 'Ghana',          code: 'GH', score: 67.6, delta:  1 },
  { name: 'Kenya',          code: 'KE', score: 67.2, delta:  0 },
  { name: 'Myanmar',        code: 'MM', score: 66.8, delta: -1 },
  { name: 'Cambodia',       code: 'KH', score: 66.5, delta:  1 },
  { name: 'Nepal',          code: 'NP', score: 66.2, delta:  0 },
  { name: 'Pakistan',       code: 'PK', score: 65.8, delta: -1 },
  { name: 'Senegal',        code: 'SN', score: 65.4, delta:  1 },
  { name: 'Rwanda',         code: 'RW', score: 65.0, delta:  0 },
  { name: 'Tanzania',       code: 'TZ', score: 64.6, delta: -1 },
  { name: 'Ethiopia',       code: 'ET', score: 64.2, delta:  1 },
  { name: 'Uganda',         code: 'UG', score: 63.7, delta:  0 },
  { name: 'Nigeria',        code: 'NG', score: 63.1, delta: -1 },
  { name: 'Haiti',          code: 'HT', score: 62.5, delta:  1 },
  { name: 'Mozambique',     code: 'MZ', score: 61.8, delta:  0 },
  { name: 'Afghanistan',    code: 'AF', score: 61.2, delta: -1 },
  { name: 'South Africa',   code: 'ZA', score: 60.7, delta:  1 },
  { name: 'Chad',           code: 'TD', score: 58.9, delta:  0 },
  { name: 'Niger',          code: 'NE', score: 57.3, delta: -1 },
  { name: 'Mali',           code: 'ML', score: 56.8, delta:  0 },
];

export const TABS = [
  { key: 'circles',   icon: 'people',  color: '#5856D6', label: 'Circles' },
  { key: 'leagues',   icon: 'trophy',  color: '#FF9F0A', label: 'Leagues' },
  { key: 'countries', icon: 'globe',   color: '#30D158', label: 'World' },
] as const;

export type TabKey = typeof TABS[number]['key'];
export const LEAGUE_CATEGORIES = ['All', 'Regional', 'Sport', 'Health', 'Lifestyle'];
